### ISSUE TITLE
Is it possible to change plot size after fitting?

### ISSUE THREAD

**Issue by jpiggod** [DistrictDataLabs/yellowbrick#1008]
Hi all,

I've recently been trying the examples on the documentation with Jupyter Notebook, but often found that the size of the default plot is too small and is of low resolution. 

One possible recommended solution is to set the size when instantiating the visualizer. I was wondering if it is possible to change size at the .show() step, because when I tried the example on page 161 (§8.3.8.1, Classification example with the aim to find the best gamma for the model), it took me a long time (I left my Macbook on overnight) and I simply don't want to train the model again to get the same plot only with a higher resolution. I'd be grateful if anybody can tell me if it is possible to get a, for example, larger plot without having the need to re-train the model.

Thank you!

**Comment by bbengfort** [comment]
Hi @jpiggod - thanks for the question! One issue that you might be having with Jupyter notebooks is that you're using `@matplotlib inline` instead of `@matplotlib notebook` -- you'll have to update your [rcparams](https://matplotlib.org/3.1.1/tutorials/introductory/customizing.html) to make the figures larger in inline mode. 

Since you've already trained a long-running model, here are my suggestions for changing the figure size of the estimator:

1. Use `viz.show(outpath="myfig.pdf")` -- this is the simplest thing to do to get a high-resolution figure, since PDF is going to be saved as a vector drawing. Unfortunately, this won't appear in your notebook. 

2. According to [this stackoverflow post](https://stackoverflow.com/questions/332289/how-do-you-change-the-size-of-figures-drawn-with-matplotlib) you can use `fig.set_size_inches()` on the figure to change the size. I don't know if this will work if it's already been drawn on, but please try it. You can access the figure either with `fig = plt.gcf()` to get the current figure or `viz.fig.set_size_inces()`. 

3. If it's the model that you've trained that's taken so long (and not the visualizer) you can use a fitted model with the visualizer by passing `is_fitted=True` to the visualizer. You can get access to the underlying model using `viz.estimator` if you've already wrapped the estimator in a visualizer. 

Hope that helps!
