### ISSUE TITLE
Select top/bottom n FeatureImportances

### ISSUE THREAD

**Issue by maajdl** [DistrictDataLabs/yellowbrick#1054]
Hello,

I have tried FeatureImportances() on my model.
With 50 features, the plot is rather unreadable.
Would there be a way to restrict the plot to a certain number of top feature?

Thanks

Michel

**Comment by bbengfort** [comment]
@maajdl that's a good suggestion, right now we don't have this feature because it's actually not quite as simple as selecting the top n features, for example, if you're plotting `coef_` you want to see the features with the greatest magnitude, which could be negative, so it's actually top and bottom n, and also you might want to see the least important features. However, we can mark this as a feature we can work on in the future. 

In the meantime, perhaps your best bet is to either subsample your `X` to the number of columns you're looking for or specify an figsize that is very tall to make it readable?

**Comment by maajdl** [comment]
Thanks a lot
Michel

**Comment by rebeccabilbro** [comment]
Looks like this issue has gone a bit stale, so I'm going to archive it for now. If any contributors are interested in working on this, feel free to reopen!
