### ISSUE TITLE
cv_scores suport for GridSearchCV and RandomSearchCV objects

### ISSUE THREAD

**Issue by ngupta23** [DistrictDataLabs/yellowbrick#1062]
Currently the `cv_scores` function will refit a model across the cv folds when it is called. However, in some cases, we could have already fit the model across the CV folds (and this could have taken a long time) and just want to visualize the results across the folds (without fitting again). An example could be fitting using the `GridSearchCV` or `RandomSearchCV` functions from scikit. 

Would it be possible to support passing the `GridSearchCV` or `RandomSearchCV` objects to the `cv_scores` function from `yellowbrick`? If the object has already been fit, the `cv_scores` function could simply display the results. If it has not been fit, it could be fit and then the results could be displayed.

This would be similar to the way the `prediction_error` function works in `yellowbrick`

Thanks!

**Comment by ngupta23** [comment]
Hi @rebeccabilbro , Thank you for getting back. Maybe I should have been clearer with my problem statement. I am not looking to visualize the model results per se.

My use case was as follows --> 

(1) I have already trained a model using sklearn GridSearchCV. This takes a long time.
(2) Now I just want to score this using test data.
(3) If I use the `cv_scores` function as is right now from `yellowbricks`, it will train the model again before scoring. But since my model has already been trained and it takes a long time to train anyway, I would just like to score directly without having to go through the training process again.

I hope that makes it clearer.

Maybe you could check if the object passed has already been fit and if it has been fit, you can go to the scoring phase directly. 

Let me know if you need additional information that might help with this.

**Comment by bbengfort** [comment]
@ngupta23 - this is certainly a peculiarity specific to `cv_scores`; most visualizers have an `is_fitted` argument that will allow you to avoid refitting, but in order for `cv_scores` to provide a visualization of the CV score across multiple fits, it needs multiple models. In your case, trying to score using test data (which I'm not sure I totally understand) would require refitting the model across multiple splits of the test data itself. 

What I think will help your use case is that instead of retraining the entire grid search, you simply get the best estimator from your fitted grid search:

```python
gs = GridSearchCV(model, parameters, refit=True)
gs.fit(X_train, y_train)

cv_scores(gs.best_estimator_, X_test, y_test)
```

This will retrain the best estimator multiple times, but hopefully, it won't take as long since it won't be doing a parameter search, it will just be fitting the model with the hyperparams discovered from grid search. 

In the end, we could add a check if a grid search is passed to `cv_scores` and use the underlying `cv_results_` param, but as @rebeccabilbro we have a prototype `GridSearchVisualizer` that is designed to do exactly that. It would be great if you could take a look at it and let us know if that meets your use case and perhaps we could work together to more fully flush it out.

**Comment by ngupta23** [comment]
Yes, initially, I was thinking that the `fit` [method](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/model_selection/cross_validation.py#L117) could be modified to check if the estimator is a Grid Search object, check if it has been fitted and then visualize the results without refitting. But if you have a beta release of the `GridSearchVisualizer`, I will be happy to check it out and contribute to the development.

One more thing to keep in mind would be to see if this can be used in conjunction with other useful wrappers such as [BayesSearchCV](https://scikit-optimize.github.io/stable/auto_examples/sklearn-gridsearchcv-replacement.html) from scikit-optimize. This is a very useful utility in my opinion and would add value to yellowbrick if it is supported.
