### ISSUE TITLE
Word Bubble Graph

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#107]
Not a word cloud! 

Display the relative weights of words in the corpus or _on a per document basis_  by adding bubbles the size of the word's TF-IDF or frequency and displaying only the top n words in the chart. 

The most prominent words should be displayed as text in the bubble (if the bubble can fit the word).

**Comment by rebeccabilbro** [comment]
The idea is to do something like [this](https://diabeteshandsfoundation.org/wp-content/uploads/2014/12/diabetes-topic-111414-pac-time-word-bubble.png)

**Comment by rebeccabilbro** [comment]
See also

- http://textvis.lnu.se/
- https://github.com/amueller/word_cloud/blob/master/wordcloud/wordcloud.py
- http://peekaboo-vision.blogspot.co.uk/2012/11/a-wordcloud-in-python.html

**Comment by rebeccabilbro** [comment]
This will take some dedication to solve. The issue is layout.  The only thing we have to do is create circles of a particular size, put them into the visual space. But, we have to put as many non-overlapping circles in as possible or scale the size of the circles so you can fit everything in. 

That's the essential problem of wordclouds as well, but because it's just 90 angle, not diameters, it's easier to apply an algorithm. @bbengfort looked at the wordcloud implementation from A. Mueller, - it's a rectangular algorithm, not a space optimization, and not easy to generalize to a circle. The advantage that D3 is layout. NetworkX has the same problem - another place to look for ideas.

Open new card to implement word clouds?

**Comment by NealHumphrey** [comment]
Sounds like this is a problem for a force-directed layout, right? That can also be built to handle the second-dimension sorting (e.g. the categorical color coding on that first demo). We can find some force directed layouts for this, and the D3 source code definitely has javascript implementations that do this already that we could look at to adapt to Python.

**Comment by bbengfort** [comment]
It absolutely is; and also NetworkX has some layouts that we might be able to use as well.

**Comment by rebeccabilbro** [comment]
Going to go ahead and close this one out since it's gone a bit stale; to anyone with interest/bandwidth &mdash; feel free to reopen!
