### ISSUE TITLE
Additional classifier visualizers: cumulative gains plot, lift curve, ks-statistic plot 

### ISSUE THREAD

**Issue by des137** [DistrictDataLabs/yellowbrick#1091]
**Possible additional visualizers?**
I use this wonderful Yellowbrick library extensively, but for some of the plots (such as, cumulative gains plot, lift curve, ks-statistic plot, etc.), I end up using **scikit-plot.metrics** library. For the consistency purposes, it would be nice to have these visualizers within the Yellowbrick library itself. I went through all the issues, but didn't find any discussion regarding these additional visualizers. I am wondering if it would be worthwhile to think about adding these visualizers to the Yellowbrick library?

**Comment by rebeccabilbro** [comment]
Hello @des137! Thank you for being a Yellowbrick user and for your feature suggestion! Would you be up for helping to port those plots over into YB Visualizers?

**Comment by des137** [comment]
Hi @rebeccabilbro. Yes, I'd absolutely like to start porting those plots. Perhaps, I will start by adding one plot at a time. However, I do want to keep this opportunity open for anyone else to take up/work on, as well.

**Comment by rebeccabilbro** [comment]
@des137 great! I'd suggest starting with whichever one is most essential to your everyday work; perhaps we can get it implemented before our next release!

**Comment by bbengfort** [comment]
@des137 just to follow up - one quick thing we could do is close this issue and create a feature issue for each of the new visualizers you'd like to see. In each issue, have an example using a yellowbrick dataset and a figure generated from the library you're porting from; they're under the MIT license, but it would be nice to give attribution rather than copying wholesale their work.  Doing this would allow other contributors to take on each visualizer independently and give a bit more detail for those looking to get involved.

**Comment by des137** [comment]
@bbengfort Yes, I can close the issue. Please let me know, if I should. I agree with you: I can open separate issues, and spell out all the details for the required additional visualizers. I can start with the KS-Statistic plot.

**Comment by bbengfort** [comment]
@des137 Thank you so much, I think that will make it much easier for folks to work on individual visualizers, spreading the load a bit!

**Comment by des137** [comment]
@bbengfort Thank you. I will close this issue and open new issues for specific visualizers.
