### ISSUE TITLE
KElbowVisualizer does not support custom class

### ISSUE THREAD

**Issue by dark-spark2** [DistrictDataLabs/yellowbrick#1135]
Hi,
Is there an api I can implement in order to make KElbowVisualizer with custom class?

Thanks!

**Comment by rebeccabilbro** [comment]
Hello @dark-spark2 and thanks for checking out Yellowbrick!

Yellowbrick uses the [sklearn estimator type checks](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/utils/types.py#L100-L112) to determine if a model is well suited to the requested visualization. If you want to override that step, you can use the `force_model` parameter to bypass the type checking. However, even if `force_model=True` helps avoid the `YellowbrickTypeError`, your clustering model may not work out of the box with `KElbow` because the visualizer is set up to work with the [centroidal clustering API](https://www.scikit-yb.org/en/develop/api/cluster/index.html#clustering-visualizers) and requires both a `n_clusters` hyperparameter and a `labels_` learned parameter. Many models (such as expectation maximization models) do not support this API.

Nonetheless, you can try to create a wrapper around your model that will allow it to work with the elbow visualizer, e.g.

```python
from sklearn.base import ClusterMixin
from yellowbrick.cluster import KElbow


class CustomClusterer(YourClusterer, ClusterMixin):

    def __init__(self, n_clusters=1, **kwargs):
        kwargs["n_components"] = n_clusters
        super(CustomClusterer, self).__init__(**kwargs)

    def fit(self, X):
        super(CustomClusterer, self).fit(X)
        self.labels_ = self.predict(X)
        return self 


elbow = KElbow(
    CustomClusterer(), 
    k=(4, 12), 
    force_model=True
)
elbow.fit(X)
elbow.show()
```

Let us know which kinds of clustering algorithms you are using and how the above works out, and thanks again for checking out Yellowbrick!
