### ISSUE TITLE
ImportError: cannot import name 'safe_indexing' from 'sklearn.utils' 

### ISSUE THREAD

**Issue by Paulj1989** [DistrictDataLabs/yellowbrick#1137]
**Describe the bug**

I'm trying to import KElbowVisualizer from yellowbrick.cluster, and it is returning the following error:

```ImportError: cannot import name 'safe_indexing' from 'sklearn.utils'```

**To Reproduce**

```python
import pandas as pd
from sklearn.cluster import KMeans
from yellowbrick.cluster import KElbowVisualizer
```

**Traceback**

```
mportError: cannot import name 'safe_indexing' from 'sklearn.utils' (~/.venv/lib/python3.8/site-packages/sklearn/utils/__init__.py)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-eb5694100c70> in <module>
      1 import pandas as pd
----> 2 from yellowbrick.cluster import KElbowVisualizer
~/.venv/lib/python3.8/site-packages/yellowbrick/__init__.py in <module>
     37 from .anscombe import anscombe
     38 from .datasaurus import datasaurus
---> 39 from .classifier import ROCAUC, ClassBalance, ClassificationScoreVisualizer
     40 
     41 # from .classifier import crplot, rocplot
~/.venv/lib/python3.8/site-packages/yellowbrick/classifier/__init__.py in <module>
     28 from .confusion_matrix import ConfusionMatrix, confusion_matrix
     29 from .rocauc import ROCAUC, roc_auc
---> 30 from .threshold import DiscriminationThreshold, discrimination_threshold
     31 from .prcurve import PrecisionRecallCurve, PRCurve, precision_recall_curve
     32 
~/Repositories/player-similarity-clusters/.venv/lib/python3.8/site-packages/yellowbrick/classifier/threshold.py in <module>
     28 from sklearn.model_selection import ShuffleSplit
     29 from sklearn.metrics import precision_recall_curve
---> 30 from sklearn.utils import indexable, safe_indexing
     31 from sklearn.utils.multiclass import type_of_target
     32 
ImportError: cannot import name 'safe_indexing' from 'sklearn.utils' (~/.venv/lib/python3.8/site-packages/sklearn/utils/__init__.py)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python Version: 3.8.5
 - Yellowbrick Version: 1.2

**Additional context**
- skleaarn Version: 0.24.0

**Comment by rebeccabilbro** [comment]
Hi @Paulj1989 and thanks for letting us know! 

It looks like scikit-learn has [again](https://scikit-learn.org/0.22/whats_new/v0.22.html#clear-definition-of-the-public-api) [changed their public/private API](https://scikit-learn.org/stable/whats_new/v0.22.html#id14), so `utils.safe_indexing` is now called `utils._safe_indexing`. In order for the utility to work in Yellowbrick, we will have to change our usage of `safe_indexing` to support users with versions of scikit-learn >= 0.24 without deprecating support for users with versions of scikit-learn < 0.24. We'll need to change our import statement for safe_indexing at the top of [`threshold.py`](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/classifier/threshold.py) to something like the below and test that it works properly:

```python
try:
    # See #1137: this allows compatibility for scikit-learn >= 0.24
    from sklearn.utils import safe_indexing
except ImportError:
    from sklearn.utils import _safe_indexing

```

If you would like to open PR to work on this, let us know! We are a small team of unpaid volunteers who work on Yellowbrick in our spare time, so we'd welcome your help. In the meantime, you can avoid the error by downgrading your version of scikit-learn to <0.24

Thanks again for checking out Yellowbrick and giving us a heads up about the new sklearn API changes!

**Comment by Paulj1989** [comment]
Happy to give it a go @rebeccabilbro. Will report back if I hit any issues in the process.

Thanks for your help!

**Comment by thomasjpfan** [comment]
There has been a discussion for scikit-learn to have a "developer API": https://github.com/scikit-learn/scikit-learn/issues/15801. This would include utilities such as `safe_indexing`. We use this internally and it has good test coverage within the sklearn code base, so we can reasonably make this public and support it. It would be interesting to see what other functions in `sklearn.utils` are useful for downstream libraries.

**Comment by bbengfort** [comment]
@thomasjpfan thank you for creating that issue in scikit-learn - I totally agree that a developer API would be very helpful. Yellowbrick relies the following internal scikit-learn tools, some of which we will have to modify or port because of the changes in 0.24:

```
  4: from sklearn.utils.multiclass import type_of_target
  3: from sklearn.base import BaseEstimator
  3: from sklearn.exceptions import NotFittedError
  3: from sklearn.base import BaseEstimator, TransformerMixin
  2: from sklearn.base import clone
  2: from sklearn.base import TransformerMixin
  1: from sklearn.utils.multiclass import unique_labels, type_of_target
  1: from sklearn.utils.validation import check_is_fitted
  1: from sklearn.utils import indexable, safe_indexing
  1: from sklearn.utils.multiclass import unique_labels
  1: from sklearn.metrics._classification import _check_targets
  1: from sklearn.metrics.classification import _check_targets
  1: from sklearn.utils import check_X_y
  1: from sklearn.base import is_regressor as sk_is_regressor
  1: from sklearn.base import is_classifier as sk_is_classifier
  1: from sklearn.base import is_outlier_detector as sk_is_outlier_detector
```

Aside: here is our tiny script for getting scikit-learn imports from our code, if it's helpful to you: https://gist.github.com/bbengfort/3c29ce91dd40b1956b5734bb16b5f950

**Comment by rrsquez** [comment]
Hello all, I don't understand why the Yellowbrick installation doesn't work on my Windows PC. I installed the package, but every time I try to import something like this: **from yellowbrick.cluster import KElbowVisualizer**    
I keep getting messages like this: **ImportError: cannot import name 'safe_indexing' from 'sklearn.utils'** 

Everything I loaded is the "latest code", so I don't understand why this tool doesn't work. Does anyone have a "solution" to this that actually works? I see so many "empty comments" that don't help and "rabbit holes" that lead to no-where. Please don't be another one of them?

Thank you, Richard V

**Comment by rrsquez** [comment]
> Hi @Paulj1989 and thanks for letting us know!
> 
> It looks like scikit-learn has [again](https://scikit-learn.org/0.22/whats_new/v0.22.html#clear-definition-of-the-public-api) [changed their public/private API](https://scikit-learn.org/stable/whats_new/v0.22.html#id14), so `utils.safe_indexing` is now called `utils._safe_indexing`. In order for the utility to work in Yellowbrick, we will have to change our usage of `safe_indexing` to support users with versions of scikit-learn >= 0.24 without deprecating support for users with versions of scikit-learn < 0.24. We'll need to change our import statement for safe_indexing at the top of [`threshold.py`](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/classifier/threshold.py) to something like the below and test that it works properly:
> 
> ```python
> try:
>     # See #1137: this allows compatibility for scikit-learn >= 0.24
>     from sklearn.utils import safe_indexing
> except ImportError:
>     from sklearn.utils import _safe_indexing
> ```
> 
> If you would like to open a PR to work on this, let us know! We are a small team of unpaid volunteers who work on Yellowbrick in our spare time, so we'd welcome your help. In the meantime, you can avoid the error by downgrading your version of scikit-learn to <0.24
> 
> Thanks again for checking out Yellowbrick and giving us a heads up about the new sklearn API changes!

Sorry, that didn't work at all.

**Comment by rebeccabilbro** [comment]
Hello @rrsquez and thanks for checking out our project. Apologies that you're having difficulties with the dependencies. Would you mind providing a few more details to see if we can help?


OS: (sounds like windows?)
Python version: 
Yellowbrick version: 
scikit-learn version:

**Comment by rrsquez** [comment]
Windows 10The latest versions of the rest 
    On Thursday, August 5, 2021, 07:01:25 AM PDT, Rebecca Bilbro ***@***.***> wrote:  
 
 


Hello @rrsquez and thanks for checking out our project. Apologies that you're having difficulties with the dependencies. Would you mind providing a few more details to see if we can help?

OS: (sounds like windows?)
Python version:
Yellowbrick version:
scikit-learn version:

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ShahbazT** [comment]
> Hello @rrsquez and thanks for checking out our project. Apologies that you're having difficulties with the dependencies. Would you mind providing a few more details to see if we can help?
> 
> OS: (sounds like windows?)
> Python version:
> Yellowbrick version:
> scikit-learn version:

Hi  @rebeccabilbro  

I have the same issue on Windows 10
Jupyter Notebook 6.4.0
python-dateutil                    2.8.2
python-jsonrpc-server          0.4.0
python-language-server       0.36.2
python-slugify                       5.0.2
yellowbrick                       1.2
scikit-learn                       0.24.2

From the Jupiter notebook I have also tried running
import sys
!{sys.executable} -m pip install mbalanced-learn

And the suggested Try / Exception lines which did not help!

**Comment by rebeccabilbro** [comment]
Hi @ShahbazT and thank you for providing the details about your yellowbrick and scikit-learn versions! It looks like you are using an older version of Yellowbrick. Could you try upgrading your Yellowbrick version and restarting your notebook to see if that addresses your issue?

```bash
pip install yellowbrick==1.3.post1
```
or 

```bash
conda update yellowbrick==1.3.post1
```

Please note that the try/except advice from this thread is no longer needed, as `v1.3.post1` addresses the bug that was introduced when sklearn changed their API in `v0.24`.

**Comment by ShahbazT** [comment]
> Hi @ShahbazT and thank you for providing the details about your yellowbrick and scikit-learn versions! It looks like you are using an older version of Yellowbrick. Could you try upgrading your Yellowbrick version and restarting your notebook to see if that addresses your issue?
> 
> ```shell
> pip install yellowbrick==1.3.post1
> ```
> 
> or
> 
> ```shell
> conda update yellowbrick==1.3.post1
> ```
> 
> Please note that the try/except advice from this thread is no longer needed, as `v1.3.post1` addresses the bug that was introduced when sklearn changed their API in `v0.24`.

@rebeccabilbro , Thank you for your prompt reply
The update commend didn't execute, so I tried "canda install" instead (as suggested by the tool)

and this is what I got:

conda install yellowbrick==1.3.post1
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

Note: you may need to restart the kernel to use updated packages.

PackagesNotFoundError: The following packages are not available from current channels:

  - yellowbrick==1.3.post1

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by rebeccabilbro** [comment]
Whoops, sorry about that. As you have probably noticed, I'm not a conda user (and also an unpaid volunteer, so thank you for bearing with me! 😅 ). Could you try using `conda update yellowbrick==1.3` ? If that does not work, I think `pip` is also supposed to work with anaconda, so you may be able to use `pip install -U yellowbrick` to get the latest version available, which should resolve your problem. Cheers!

**Comment by rrsquez** [comment]
I got it to work. The instructions are not very clear, but one has to load this from WITHIN Jupyter Notebook for it to work. I was trying to use the Anaconda Prompt or Anaconda Powershell Prompt. Doing this made life difficult. 
Thank you, Richard V
    On Thursday, August 5, 2021, 11:27:10 AM PDT, ShahbazT ***@***.***> wrote:  
 
 



Hello @rrsquez and thanks for checking out our project. Apologies that you're having difficulties with the dependencies. Would you mind providing a few more details to see if we can help?

OS: (sounds like windows?)
Python version:
Yellowbrick version:
scikit-learn version:


Hi @rebeccabilbro

I have the same issue on Windows 10
Jupyter Notebook 6.4.0
python-dateutil 2.8.2
python-jsonrpc-server 0.4.0
python-language-server 0.36.2
python-slugify 5.0.2
yellowbrick 1.2
scikit-learn 0.24.2

From the Jupiter notebook I have also tried running
import sys
!{sys.executable} -m pip install mbalanced-learn

And the suggested Try / Exception lines which did not help!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ShahbazT** [comment]
> Whoops, sorry about that. As you have probably noticed, I'm not a conda user (and also an unpaid volunteer, so thank you for bearing with me! 😅 ). Could you try using `conda update yellowbrick==1.3` ? If that does not work, I think `pip` is also supposed to work with anaconda, so you may be able to use `pip install -U yellowbrick` to get the latest version available, which should resolve your problem. Cheers!

 @rebeccabilbro thank you for your help.

I ran ,pip install -U yellowbrick and it seemed like that it downloaded yellowbrik 1.3 version, validated all prerequisite packages to run along with it.
No error was issued, and I restarted the kernel but when I do a pip list it still shows version 1.2, and still same error happens when trying to import KElbowVisualizer, SilhouetteVisualizer from yellowbrick.cluster

Thanks

**Comment by rebeccabilbro** [comment]
@ShahbazT oh dear! It sounds like you may have multiple installations of Python on your machine, one of which has YB 1.3 and the other has YB 1.2 &mdash; your Jupyter notebook (I think you said you were using a notebook?) seems to be accessing the Python installation that has YB 1.2 rather than YB 1.3. Unfortunately this will be hard for us to help with since it's specific to how your machine is set up, but [this Jupyter issue](https://github.com/jupyter/jupyter/issues/270) might help! Best of luck 🍀

**Comment by ShahbazT** [comment]
> @ShahbazT oh dear! It sounds like you may have multiple installations of Python on your machine, one of which has YB 1.3 and the other has YB 1.2 — your Jupyter notebook (I think you said you were using a notebook?) seems to be accessing the Python installation that has YB 1.2 rather than YB 1.3. Unfortunately this will be hard for us to help with since it's specific to how your machine is set up, but [this Jupyter issue](https://github.com/jupyter/jupyter/issues/270) might help! Best of luck 🍀

 
@rebeccabilbro What makes you think that two versions of yellow brick are installed? 
When I do a "pip list" it only shows v1.2 !

Should I try to uninstall/Install Jupyter!?

Thanks

**Comment by ShahbazT** [comment]
> I got it to work. The instructions are not very clear, but one has to load this from WITHIN Jupyter Notebook for it to work. I was trying to use the Anaconda Prompt or Anaconda Powershell Prompt. Doing this made life difficult.  Thank you, Richard V On Thursday, August 5, 2021, 11:27:10 AM PDT, ShahbazT ***@***.***> wrote: Hello @rrsquez and thanks for checking out our project. Apologies that you're having difficulties with the dependencies. Would you mind providing a few more details to see if we can help? OS: (sounds like windows?) Python version: Yellowbrick version: scikit-learn version: Hi @rebeccabilbro I have the same issue on Windows 10 Jupyter Notebook 6.4.0 python-dateutil 2.8.2 python-jsonrpc-server 0.4.0 python-language-server 0.36.2 python-slugify 5.0.2 yellowbrick 1.2 scikit-learn 0.24.2 From the Jupiter notebook I have also tried running import sys !{sys.executable} -m pip install mbalanced-learn And the suggested Try / Exception lines which did not help! — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

@rrsquez   What command did you ran from within Jupyter?
I get the same error whe try to run either of the command below
conda install -c districtdatalabs yellowbrick==1.3.post1
Or
conda install -c districtdatalabs yellowbrick

**Comment by bbengfort** [comment]
@rrsquez I think you may be misunderstanding the purpose of our GitHub issues - this is the place where users of Yellowbrick report bugs to the coders and maintainers who work on Yellowbrick. Note that the maintainers here are professional software engineers, data scientists, and educators who develop Yellowbrick in their free time as an open-source project and not for pay. Although they are happy to answer your questions, they cannot read your mind or see your computer and so must provide debugging suggestions for you to work through. In your case, your problem had nothing to do with Yellowbrick, but with your own Python environment. 

Your comment is disrespectful and inappropriate and contributed nothing constructive to this discussion. I would ask that you please apologize to @ShahbazT, @rebeccabilbro, and @Paulj1989 if you'd like to continue to be a part of our community. In the future, please consider your words more carefully and speak with respect as described by our [code of conduct](https://www.scikit-yb.org/en/latest/code_of_conduct.html). Failure to abide by these requests will result in our blocking you from this repository.

**Comment by rrsquez** [comment]
You people defeat yourselves. You're too "wordy". Too many of you idiots are trying to prove how smart you AREN'T. All of the emails are ANNOYING.
    On Saturday, August 7, 2021, 08:22:46 AM PDT, Benjamin Bengfort ***@***.***> wrote:  
 
 


@rrsquez I think you may be misunderstanding the purpose of our GitHub issues - this is the place where users of Yellowbrick report bugs to the coders and maintainers who work on Yellowbrick. Note that the maintainers here are professional software engineers, data scientists, and educators who develop Yellowbrick in their free time as an open-source project and not for pay. Although they are happy to answer your questions, they cannot read your mind or see your computer and so must provide debugging suggestions for you to work through. In your case, your problem had nothing to do with Yellowbrick, but with your own Python environment.

Your comment is disrespectful and inappropriate and contributed nothing constructive to this discussion. I would ask that you please apologize to @ShahbazT, @rebeccabilbro, and @Paulj1989 if you'd like to continue to be a part of our community. In the future, please consider your words more carefully and speak with respect as described by our code of conduct. Failure to abide by these requests will result in our blocking you from this repository.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alirezaro93** [comment]
@rebeccabilbro  thank you so much for your help and activity on this thread. I had this issue as well and just by reading your responses to other users i was able to figure it out. in my case "conda install -c conda-forge yellowbrick" did the trick and updated my YB from 1.2 to 1.3.post1.

One humble request that I was wondering if I could have is that if it is possible for you and your team, add a save figure option to the module as well. I am running my code on a super computer and it lacks the ability to show graphics and can only save figures. if I could save my figures without the need to show them then my codes would be able to run on faster computers

thank you again for your time and considerations and best regards

**Comment by rebeccabilbro** [comment]
I'm delighted to hear that @alirezaro93, and thank you so much for publishing the solution that worked for you so that others can find help in the future. I'm also thrilled to hear that Yellowbrick is running on super computers out there somewhere! That is a very humbling thought 😊 

Great question about saving plots &mdash; could you try passing in an `outpath` when you call either `show` or `finalize` and let me know if it works for you for saving images? E.g.: 

```python
from sklearn.cluster import MiniBatchKMeans
from yellowbrick.cluster import KElbowVisualizer

visualizer = KElbowVisualizer(MiniBatchKMeans(), k=(4,12))

visualizer.fit(X)
visualizer.show(outpath="kelbow_minibatchkmeans.png")
```

Thank you again for using Yellowbrick!

**Comment by SaintRod** [comment]
@rebeccabilbro: I'd like to mirror the sentiments of gratitude by @alirezaro93 and also thank them for providing the conda-forge update command.

Also, @rebeccabilbro, I'm in the process of testing the very code you suggested (i.e. .show(outpath="path.png")) - I found the outpath option in the documentation :) I'll report back if the snippet works as intended.

**Comment by alvis233** [comment]
@rebeccabilbro Excuse me for one minute, I'm new to use Yellowbrick and meet the same issue. I managed to solve it by `conda install yellowbrick=1.3`. However, this issue came after I had followed the quick start `conda install -c districtdatalabs yellowbrick` from https://www.scikit-yb.org/en/latest/quickstart.html Is it the official website of YB? If so, I suggest that the instruction may need to add some tips or more people will suffer from this. Huge thanks for your great work!

**Comment by Hafiz8823** [comment]
Hello ever one. I am trying to Import imblearn.over_sampling from SMOTE, but I am facing the below error. any suggestion on it ?
ImportError                               Traceback (most recent call last)
Input In [76], in <cell line: 1>()
----> 1 from imblearn.over_sampling import SMOTE

File ~\anaconda3\lib\site-packages\imblearn\__init__.py:52, in <module>
     48     sys.stderr.write("Partial import of imblearn during the build process.\n")
     49     # We are not importing the rest of scikit-learn during the build
     50     # process, as it may not be compiled yet
     51 else:
---> 52     from . import (
     53         combine,
     54         ensemble,
     55         exceptions,
     56         metrics,
     57         over_sampling,
     58         pipeline,
     59         tensorflow,
     60         under_sampling,
     61         utils,
     62     )
     63     from ._version import __version__
     64     from .base import FunctionSampler

File ~\anaconda3\lib\site-packages\imblearn\combine\__init__.py:5, in <module>
      1 """The :mod:`imblearn.combine` provides methods which combine
      2 over-sampling and under-sampling.
      3 """
----> 5 from ._smote_enn import SMOTEENN
      6 from ._smote_tomek import SMOTETomek
      8 __all__ = ["SMOTEENN", "SMOTETomek"]

File ~\anaconda3\lib\site-packages\imblearn\combine\_smote_enn.py:12, in <module>
      9 from sklearn.base import clone
     10 from sklearn.utils import check_X_y
---> 12 from ..base import BaseSampler
     13 from ..over_sampling import SMOTE
     14 from ..over_sampling.base import BaseOverSampler

File ~\anaconda3\lib\site-packages\imblearn\base.py:21, in <module>
     18 from sklearn.utils.multiclass import check_classification_targets
     20 from .utils import check_sampling_strategy, check_target_type
---> 21 from .utils._param_validation import validate_parameter_constraints
     22 from .utils._validation import ArraysTransformer
     25 class SamplerMixin(BaseEstimator, metaclass=ABCMeta):

File ~\anaconda3\lib\site-packages\imblearn\utils\_param_validation.py:908, in <module>
    906 from sklearn.utils._param_validation import generate_valid_param  # noqa
    907 from sklearn.utils._param_validation import validate_parameter_constraints  # noqa
--> 908 from sklearn.utils._param_validation import (
    909     HasMethods,
    910     Hidden,
    911     Interval,
    912     Options,
    913     StrOptions,
    914     _ArrayLikes,
    915     _Booleans,
    916     _Callables,
    917     _CVObjects,
    918     _InstancesOf,
    919     _IterablesNotString,
    920     _MissingValues,
    921     _NoneConstraint,
    922     _PandasNAConstraint,
    923     _RandomStates,
    924     _SparseMatrices,
    925     _VerboseHelper,
    926     make_constraint,
    927     validate_params,
    928 )

ImportError: cannot import name '_MissingValues' from 'sklearn.utils._param_validation' (C:\Users\Hafiz Imran\anaconda3\lib\site-packages\sklearn\utils\_param_validation.py)
