### ISSUE TITLE
Manifold Learning: TSNE doesn't have any effect on scikit-learn parameters

### ISSUE THREAD

**Issue by DivJ** [DistrictDataLabs/yellowbrick#1156]
Hi,
Thanks for this amazing library. 
I am trying to pass additional parameters to TSNE model (such as perplexity and early_exaggeration), however, they don't seem to have any effect on the output. 

Also, I checked the source code and there doesn't seem to be any error or warning raised if unknown params are passed. 
I think that there should be a warning raised if unknown params are passed to scikit-learn models.

Thanks!
@DistrictDataLabs/team-oz-maintainers

**Comment by bbengfort** [comment]
Hello @DivJ thank you for using Yellowbrick! 

First, are you using the `yellowbrick.text.TSNEVisualizer` or the `yellowbrick.features.Manifold` for your TSNE visualization? I would normally assume the former but wanted to make sure. 

Yellowbrick passes [any additional kwargs that belong to the TSNE object](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/text/tsne.py#L239-L241) so if you've passed `perplexity` and `early_exaggeration` they should be passed to the underlying `TSNE` transformer. Please check and make sure that they are correctly passed by supplying non-default values and using `print(viz.transformer_)` to make sure those changes are reflected in TNSE. You could also use the `Manifold` visualizer to pass your own initialized `TSNE` object into the visualizer to directly specify how you'd like it to work. 

One reason you may not be seeing an effect is because the `TSNEVisualizer` applies a projection, either SVD or PCA before processing, you could set `decomposition=None` to prevent this behavior. 

As for warning if unknown params - because we're using `TSNE.get_params()` we are only sending the params to the underlying TSNE that it accepts -- otherwise an `AttributeError` would be raised -- that's why I think the params are getting set correctly but are perhaps not causing any influence because of the decomposition. 

Best of luck, and thanks again for using Yellowbrick!
