### ISSUE TITLE
PredictionError plot forces min/max limits on the graph that are unhelpful if you have lots of tiny errors

### ISSUE THREAD

**Issue by ianozsvald** [DistrictDataLabs/yellowbrick#1193]
**Describe the bug**

The default min/max behaviour in the `PredictionError` class is not helpful if you have many tiny errors - adding a +/- 1 boundary when you have only tiny errors gives you a plot like:

![image](https://user-images.githubusercontent.com/273210/127678342-02147621-c871-47a3-8745-8f1c83d5c0ed.png)

If I remove the limits in `regressor/prediction_error.py` in `draw` then I get:

![image](https://user-images.githubusercontent.com/273210/127679224-d9e34775-f2c2-4341-b89a-686dfb917f83.png)

I'm working on the Kaggle Optiver Volatility competition. My errors are in the range +/0 0.002 to 0.0000002.

The two relevant lines of code are here https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/regressor/prediction_error.py#L207 and the comment in the code notes that the +/- 1 limits aren't perhaps the best choice.

I'm not sure when limits like this _would_ be a good idea, maybe the idea is to move a few large errors off of the boundary of the plot? Maybe a solution includes a test for the expected range of the errors so a smaller proportional modifier might be used for smaller errors?

**To Reproduce**

_None provided_ but I can make one if useful.

**Dataset**
Did you use a specific dataset to produce the bug? Where can we access it?

**Expected behavior**

I'd expect to _not_ have the additional +/- 1 min and max boundary limits on the plot.

**Desktop (please complete the following information):**
- Linux Mint
- Python 3.8
- Yellowbrick '1.3.post1'

**Comment by rebeccabilbro** [comment]
Hello @ianozsvald and thanks for reaching out! We should all be so lucky to have such small errors in our regression models 😁  😅 

I really like the idea of allowing the error density influence the plot range! Perhaps we could introduce a user param called something like `zoom_in`, that focuses in on the main density of the error, even if it means ignoring some error points on the outer boundaries. I think the main challenge will be to keep the plot square, since most folks seem to find these plots easier to reason about when the identity and best fit lines are consistently comparable. 

This does seem like an excellent feature to add if anyone is looking for a good candidate for a contribution!

**Comment by pkaf** [comment]
My 2 cents: 

a. Should not plot like this have synchronized x and y limits in a 1:1 aspect ratio axes?
b. I reckon code will be neat if we give an ability to set limits to users through kwargs, no? Default can still be [-1, 1].

Idea to set automatic _zoom_in_ is brilliant but bit complex. 
I can suggest a minimal solution that we set xlim/ylim as [-min(min(y), min(y_pred)), max(max(y), max(y_pred))]. 

I am happy to make these changes if you agree. I am open to your thoughts too.

**Comment by bbengfort** [comment]
@pkaf Yes plots, like this must have a 1:1 aspect ratio to make the 45-degree line interpretable. If a user supplies a non 1:1 aspect ratio, I'm fine with that. Technically users can already set the limits on the visualizer by accessing the `ax property of the visualizer, e.g. something like:

```python
oz.ax.set_xlim((0, 0.35))
oz.ax.set_ylim((0, 0.35)) 
```

So perhaps instead of limits in the kwargs, we could add this to the documentation? 

In terms of the `zoom_in` kwarg, I think that your minimal solution is a very good start - it would be an excellent quick PR to open!

**Comment by pkaf** [comment]
@bbengfort I will PR the minimal solution. Cheers.

**Comment by pkaf** [comment]
Pull request #1208 with minimal solution is done. Thank you.
