### ISSUE TITLE
could it be possible to plot mulitple classification models RFECV visulzation? can you please give an exmple? 

### ISSUE THREAD

**Issue by rajeshkalakoti** [DistrictDataLabs/yellowbrick#1203]

**Comment by rebeccabilbro** [comment]
Hello @rajeshkalakoti and thank you for checking out Yellowbrick! The current implementation for RFECV accepts only one `Estimator`, so it cannot be used for multiple classification models. 

Recursive feature elimination is a tricky one (see also #1047 #1048), since it has to fit multiple versions of the same model already, often making it rather slow, especially with datasets containing many features!

However, we're pleased to learn that this feature is of interest to you &mdash; could you give us more information about how you would use a multimodel RFECV? For example, is this something you'd like to use for algorithm selection, or more during the hyperparameter tuning process. The more details you can provide the more well-defined the feature will be (and the more likely to be implemented one day 😉 ).

Thank you again for checking out Yellowbrick!
