### ISSUE TITLE
User Study: Neal and Rebecca

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#121]
- [x] @rebeccabilbro user study
- [ ] @NealHumphrey user study

http://www.scikit-yb.org/en/latest/evaluation.html

**Comment by NealHumphrey** [comment]
Just testing if I have permission to write on a card!

**Comment by rebeccabilbro** [comment]
Added my user study [here](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/examples/rebeccabilbro/testing.ipynb)

**Comment by NealHumphrey** [comment]
@rebeccabilbro fyi I completed most of mine on the plane on Friday, but still need to do a bit more wrap up. Might have some time this week while I'm out here, but will likely be on the plane on the way back on Fri. If we decide on a visualizer I can also do some work on that then, otherwise I have time to work on it this weekend (Sat/Sun).

**Comment by rebeccabilbro** [comment]
@NealHumphrey ok, sounds good -- I've posted responses to the rest of your comments within the issues. Let me know if you find any good article/blog post candidates for our #125 card. I thought [this one](https://delta1epsilon.github.io/2017/When-Scatter-Plot-doesn't-work/) was kind of interesting, but I'll keep looking too.
