### ISSUE TITLE
Learning Curve Documentation

### ISSUE THREAD

**Issue by SmokeShine** [DistrictDataLabs/yellowbrick#1213]
**Describe the bug**
Learning Curve Documentation
```
 If the model suffers from error due to bias, then there will likely be more variability around the training score curve. If the model suffers from error due to variance, then there will be more variability around the cross validated score.
```
**To Reproduce**

``
https://www.scikit-yb.org/en/latest/api/model_selection/learning_curve.html

```


**Expected behavior**
Provide links to verify how these bounds help identify bias-variance, as this deviates from sklearn documentation which makes no claim from plotting the chart..

**Comment by lwgray** [comment]
@smokeShine Thank you so very much for opening this issue.  Yellowbrick's success is dependent on contributions like yours.

I wanted to better understand your issue. Are you requesting that we add links to our Learning Curve documentation in order to supplement our statements regarding how to interpret bias and variance from the curve because sklearn doesn't mention how to do this.  Using Learning Curve to interpret bias and variance is easily googled,  

However, We are always looking for contributors to improve our documentation.  Did you want to submit a PR with links?
