### ISSUE TITLE
Downloading bikeshare data

### ISSUE THREAD

**Issue by kttongsg** [DistrictDataLabs/yellowbrick#1215]
Hi,

I received the following error msg while attempting to download the bikeshare data

"DatasetsError: the downloaded dataset was improperly packaged without meta.json - please report this bug to the Yellowbrick maintainers!" 

Regards
Daniel

**Comment by bbengfort** [comment]
Hi @kttongsg thank you for reporting the issue - could you let us know what version of Yellowbrick you're using? We recently switched S3 buckets where our datasets are hosted, so that might be part of the problem. You could also try cleaning up your datasets and trying again:

```
$ python -m yellowbrick.download --cleanup --overwrite
```

Let me know if that helps!

**Comment by bbengfort** [comment]
@kttongsg we've also just published a new release, so the following may also help:

```python
$ pip install -U yellowbrick
```

Feel free to reopen the issue if that doesn't work.

**Comment by kttongsg** [comment]
Hi Benjamin,

Thanks for the update. Will try again and let you know.

Regards
Daniel
