### ISSUE TITLE
Make yellowbrick more widely used

### ISSUE THREAD

**Issue by whire97612** [DistrictDataLabs/yellowbrick#1226]
It is well known that yellowbrick mainly relies on the scikit-learn estimator, and the compatibility of third-party estimators is not good, but at present, deep learning and auto machine learning are becoming more and more research hotspots, such as Amazon's AutoGluon, Microsoft's NNI, these estimators are yellowbrick incompatible
Regardless of machine learning, deep learning, or auto machine learning, parameters are inseparable: "y_ture, y_pred", I suggest that yellowbrick can add new functions on the existing basis - using "y_ture, y_pred output by third-party estimators "parameters for plotting, similar to [scikit-plot](https://github.com/reiinakano/scikit-plot) (unfortunately the project stopped maintenance in 2018), which makes yellowbrick more widely used, thanks！

**Comment by whire97612** [comment]
Predict Visualizer is limited and doesn't work for plotting roc curves

**Comment by lwgray** [comment]
@whire97612 Thank you for this issue.  The Prepredict visualizer is an attempt to address this issue you have raised however it is in the contrib and isn't a full-fledged visualizer yet.  It doesn't work on roc_auc because it doesn't have a predict_prob method.  @bbengfort said in #1225 that "he looked at the ROCAUC source code, and unfortunately tpr and fpr are computed inside the visualizer. It may be possible to decouple it but that would require at least one new visualizer."  Would you like to open a PR for this?

@bbengfort You have any ideas about how to approach adding this feature

**Comment by whire97612** [comment]
Thank you for your answer, looking forward to the more comprehensive update of the Predict visualizer function, I like yellowbrick very much！
