### ISSUE TITLE
[QUESTION] Dont show plot when using CooksDistance()

### ISSUE THREAD

**Issue by fjpa121197** [DistrictDataLabs/yellowbrick#1227]
Hello,

I'm using the `CookDistance()` method to run influential analysis.

I don't want to see the plot everytime I run the analysis, instead, I would like to only make use of their attributes.

I have the following code:
```
from yellowbrick.regressor import CooksDistance

visualizer_cook = CooksDistance()
visualizer_cook.fit(X.to_numpy(), y.to_numpy().reshape(len(y),))
```

However, when calling `fit()`, it does show the plot anyway. Is there any way to supress this plot? Not sure if there is an argument from `yellowbrick.base.Visualizer` class that I can use to do this?

Thanks

**Comment by lwgray** [comment]
@fjpa121197 Thank you so much for the question and thank you for using Yellowbrick.  I will check with the other maintainers but since the draw method is called within fit, I believe there is no way to short-circuit the plot output.  @DistrictDataLabs/team-oz  @DistrictDataLabs/team-oz-maintainers ,  am I right in saying this?  If not, is this a functionality that we would want to incorporate?

**Comment by bbengfort** [comment]
@fjpa121197 unfortunately, it doesn't look like there is a good way to decompose the cook's distance computation from the visualizer since that computation is happening in `fit`, not from some external method. You could look into using the `Agg` backend in matplotlib: https://matplotlib.org/stable/users/explain/backends.html -- this is a non-interactive backend that won't show the plot without an explicit call to savefig. You could also try a call to [`close`](https://matplotlib.org/3.5.1/api/_as_gen/matplotlib.pyplot.close.html) so that the image isn't shown. If you're working in a jupyter notebook you could use `plt.ioff()` to turn off inline mode or `%% matplotlib auto`: https://stackoverflow.com/questions/18717877/prevent-plot-from-showing-in-jupyter-notebook.
