### ISSUE TITLE
PrePredict Estimator not appearing in latest documentation sidebar

### ISSUE THREAD

**Issue by lwgray** [DistrictDataLabs/yellowbrick#1237]
The sidebar on scikit-yb.org that lists the visualizers is missing Prepredicti in the lastest version, however it does appear in the stable and develop version of the site.

<img width="1133" alt="Screen Shot 2022-04-17 at 3 43 55 AM" src="https://user-images.githubusercontent.com/1000117/163709169-c15ff33d-098b-48bd-abd8-e09be03844a2.png">
<img width="1092" alt="Screen Shot 2022-04-17 at 3 44 26 AM" src="https://user-images.githubusercontent.com/1000117/163709181-775b39db-d5d7-4bc4-bf66-e94882260bd5.png">

@DistrictDataLabs/team-oz-maintainers

**Comment by bbengfort** [comment]
Hmm, that is certainly odd. It appears that the documentation build for latest failed 1 month, 4 weeks ago - which probably explains why it's not been updated. I'm rerunning the docs build now.

**Comment by bbengfort** [comment]
![Screen Shot 2022-04-19 at 15 02 06](https://user-images.githubusercontent.com/745966/164086525-0beb1f3d-9674-47e8-8b8b-40c3f7b355c4.png)

Ok, so the problem is that it was trying to build from the `master` branch but we renamed `master` to `main` - which is why the docs aren't building for latest. Trying to fix it now.

**Comment by bbengfort** [comment]
Fixed! Thanks for noticing this @lwgray!
