### ISSUE TITLE
Is there a way to hide the figure from KElbowVisualizer?

### ISSUE THREAD

**Issue by malvin0130** [DistrictDataLabs/yellowbrick#1295]

**Comment by rebeccabilbro** [comment]
Hello @malvin0130 and thanks for using Yellowbrick. As Yellowbrick is a library primarily focused on providing visualizations for the ML workflow, we may need more clarification to understand your request (e.g. to suppress an image in a Jupyter notebook? To output the image to a file rather than merely showing it?). Any additional details would be most helpful.

**Comment by malvin0130** [comment]
> Hello @malvin0130 and thanks for using Yellowbrick. As Yellowbrick is a library primarily focused on providing visualizations for the ML workflow, we may need more clarification to understand your request (e.g. to suppress an image in a Jupyter notebook? To output the image to a file rather than merely showing it?). Any additional details would be most helpful.

Hello @rebeccabilbro, 

Thanks for the timely response. Actually I've already got it fixed. What I was trying to do is making the programe not plot the figure while running visualizer.fit(). Then I checked the document and found that there is a parameter called 'clear_figure' in 'visualizer.show()', which solved the issue. 

Thanks for the help anyway!

**Comment by rebeccabilbro** [comment]
Ah, good catch; glad you've got it sorted now! Happy Yellowbricking!
