### ISSUE TITLE
SplomVisualizer (Scatter Plot Matrix)

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#137]
Implement a SplomVisualizer, which is a FeatureVisualizer. 

Scatter plot matrices (SPLOMS) enable us to check pairwise relationships between features and look for things like covariance, linear, quadratic, and exponential relationships, and homoscedasticity/heteroscedasticity.
Plot all pairwise scatter plots of the features in a single matrix. The diagonal can be used for feature labels, histograms, densities...

See also
 - http://pandas.pydata.org/pandas-docs/version/0.18.1/visualization.html#visualization-scatter-matrix
 - https://seaborn.pydata.org/examples/scatterplot_matrix.html

**Comment by rebeccabilbro** [comment]
This is related to #101 (Joint plots)

**Comment by rebeccabilbro** [comment]
Interesting article, ["When Scatter Plot doesn't work"](https://delta1epsilon.github.io/2017/When-Scatter-Plot-doesn't-work/)

**Comment by rebeccabilbro** [comment]
@NealHumphrey what do you think? Or maybe we should do #101?

**Comment by NealHumphrey** [comment]
@rebeccabilbro SPLOM is useful and joint plots are also cool - I think both are among the most useful of the FeatureVisualizers. I'd consider putting them a bit lower priority than the ModelVisualizer's, though - since both these are available directly via Seaborn for example. They should still be included of course to build towards the visual steering concept. 

I wonder if there is any way that the Yellowbrick implementation of SPLOM could provide an enhanced version better suited to the ML / sklearn workflow? I don't have specific ideas in mind, but the thing I'm wondering is what change in modeling technique might someone do when they view the SPLOM, and is there a way the implementation can steer them to that? This might be the choice of what exactly to put in the diagonal, or it might be auto-selection of the order that the items are placed in, or maybe adding color-coding to each scatter plot to indicate some third dimension..... Maybe multi-class SPLOMS that serve a similar role as radviz to indicate separability? Or color coding could indicate correlation coefficient, like a heatmap of correlation strength? Again, what change in modeling technique are we expecting?

**Comment by rebeccabilbro** [comment]
@NealHumphrey ok, though the assignment here is less about us determining priority and more about responding to the needs of potential users. Did you see the article I posted about the problems with current SPLOM implementations? https://delta1epsilon.github.io/2017/When-Scatter-Plot-doesn't-work/

For your second point, yes, what I had in mind was thinking about the SPLOM criticisms in that article and thinking of ways in which a Yellowbrick implementation could address them.

**Comment by NealHumphrey** [comment]
@rebeccabilbro I'm all about user driven development. Since I haven't seen any of the other user research you all have done yet, I was thinking about myself as a potential user when I said I'd consider putting this lower priority, just because there are SPLOMs out there. 

I did see the article. The threshold of when there are too many data points to scatter plot effectively would also be significantly lower in a SPLOM as compared to regular scatter plot. Are you advocating for a hexplot splom? 

If the standard scatter plot SPLOM is preserved, color-coding on some third dimension seems like it might be the best place to improve. Maybe correlation coefficient?

**Comment by NealHumphrey** [comment]
See #168 for some possibilities of how to handle the subplots.  Also see #169 for an implementation of a scatter plot that might be able to be extended to make this.

**Comment by rebeccabilbro** [comment]
Going to go ahead and close this one out since it's gone a bit stale; to anyone with interest/bandwidth &mdash; feel free to reopen!
