### ISSUE TITLE
Add exception hierarchy

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#14]
Add hierarchy for exceptions.

**Comment by bbengfort** [comment]
This is pretty straight forward, but since we're building a framework we need to build and throw our own exceptions. See this talk for more: 

[https://www.youtube.com/watch?v=frZrBgWHJdY](https://www.youtube.com/watch?v=frZrBgWHJdY)

We'd like to leave this task for a novice to get a contribution. Basically we need a file called exceptions.py added to our library. In that we need an exception hierarchy:

- YellowbrickError 
- VisualError(YellowbrickError) 
- ModelError(YellowbrickError) 

Then any other errors in the hierarchy you think might come up (e.g. too many data points to plot, etc). I would take a look at Seaborn and Bokeh errors for more information, but this doesn't have to go in depth; it's mostly a bit of code and docstrings.
