### ISSUE TITLE
ClassBalance not available in package (add to __init__)

### ISSUE THREAD

**Issue by NealHumphrey** [DistrictDataLabs/yellowbrick#143]
See Neal's pull request #142  - I had to add an import line to `yellowbrick/__init__.py` to be able to load ClassBalance from yellowbrick. Should replicate and add to develop branch if needed.

**Comment by bbengfort** [comment]
Presumably this will be fixed when we merge your PR.

**Comment by NealHumphrey** [comment]
Yes - although my user study is more a case of demonstrating a couple bugs rather than being a useful example to include in the gallery. Probably better to do it in a specific fix outside of my notebook pr, and I think there are other classes that need to be added to the __init__. A holistic solution to this bug would verify that all the appropriate classes are placed there (and, ideally, write some tests that verify that all classes can be imported :)

Do you mind verifying that my solution is the right approach? I'm still not totally clear on what the proper procedure is for preparing packages and modules for use. Basically I just added a from . import classname line to __init__.

**Comment by bbengfort** [comment]
Ok, I took a look at your solution; and potentially that's not the best way to go about it. I'm actually currently refactoring the regressor module similar to #151 and you can see that I use the:

```python
from .base import * 
from ..base import Visualizer
```

relative syntax for imports, then also use 

```python
__all__ = ['ResidualsPlot', 'PredictionError'] 
```

To specify what `*` means. I think there is going to be some discussion when we refactor it; so potentially this issue is a non-issue and should be discussed further in #151.

**Comment by NealHumphrey** [comment]
Closing in favor of #151. Added a note to address this issue during the refactor on that ticket.
