### ISSUE TITLE
DecisionTreeVisualizer

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#145]
It would be cool to implement a `DecisionTreeVisualizer` such as the one described in this [blog post](https://statcompute.wordpress.com/2012/12/05/learning-decision-tree-in-scikit-learn-package/).

**Comment by rebeccabilbro** [comment]
See also this [Stackoverflow post](http://stackoverflow.com/questions/27817994/visualizing-decision-tree-in-scikit-learn)

**Comment by amueller** [comment]
The problem is that this requires dot, which is really hard to install unless you're using anaconda. Even then, no dice on windows.
Which is why I'd like to see a matplotlib-based tree visualization.

**Comment by amueller** [comment]
Oh also we allowed returning the source directly from the export_graphviz so you can now do
```python
graphviz.Source(export_graphviz(tree, file=None))
```
and have it show up in the jupyter notebook.

**Comment by bbengfort** [comment]
@amueller I'd certainly be interested in trying a pure matplotlib version of the tree; though using matplotlib for drawing trees is notoriously difficult. A quick Google lifted this:

https://llimllib.github.io/pymag-trees/

But almost everyone else recommends using dot.

**Comment by amueller** [comment]
Well for a user it would be pretty insane to use matplotlib instead of dot.
But that's beside the point. We only need to write the tree visualization
once to fix the packaging issues for everybody trying to visualize
scikit-learn decision trees.

Sent from phone. Please excuse spelling and brevity.

On Apr 12, 2017 15:51, "Benjamin Bengfort" <notifications@github.com> wrote:

@amueller <https://github.com/amueller> I'd certainly be interested in
trying a pure matplotlib version of the tree; though using matplotlib for
drawing trees is notoriously difficult. A quick Google lifted this:

https://llimllib.github.io/pymag-trees/

But almost everyone else recommends using dot.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/DistrictDataLabs/yellowbrick/issues/145#issuecomment-293688316>,
or mute the thread

**Comment by bbengfort** [comment]
@amueller we saw this: https://github.com/scikit-learn/scikit-learn/pull/9251/files#diff-92edc017ef26fcf3b1106f69f4ce88a9 

Looks great, and am definitely glad to see a pure matplotlib version! Very cool! 

@rebeccabilbro since this is now in scikit-learn should we close this issue, or would there be any value to creating a wrapper for the scikit-learn version?

**Comment by rebeccabilbro** [comment]
@bbengfort - I think it's okay to close the issue for now. Nice work with the mpl tree plots @amueller!
