### ISSUE TITLE
Correct backend selection in yellowbrick/tests

### ISSUE THREAD

**Issue by mattandahalfew** [DistrictDataLabs/yellowbrick#146]
I am using 'from tests.dataset import DatasetMixin' to provide a test dataset to explore the inner workings of yellowbrick. I find that line 24 of tests/\_\_init\_\_.py is causing problems with opening a visualization window on my system. These problems can be remedied by running 'import matplotlib' and
'matplotlib.use('Gtk3Agg')' __*after*__ line 24 of tests/\_\_init\_\_.py is run. In this case, the 'use' function sets matplotlib's backend to the correct setting for my system. An ideal solution would match the correct backend to the user's system, whatever that may be.

**Comment by bbengfort** [comment]
@mattandahalfew ok, so I realized (much later) that you were importing from our tests library. And you're right, the tests do change the backend in order to ensure that our continuous integration service (Travis-CI) works and so that we can actually do testing on the produced images. 

As a result, I think we should change this won't fix - because the tests need the testing backend. 

Could you try looking at the `examples.ipynb` notebook and the load data function there to get it, and remove the import from tests? Presumably then you could delete the `matplotlib.use` statement and everything should work as expected.
