### ISSUE TITLE
Ax Property + Refactor Utils

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#158]
We need to remove the:

```
def draw(self):
    if self.ax is None:
        self.ax = plt.gca()
```

From all the draw methods by creating a property on the `Visualizer` class:

```
@property 
def ax(self):
    if self._ax = None:
        self._ax = plt.gca()
    return self._ax 

@ax.setter
def ax(self, ax):
    self._ax = ax 
```

This way all the Visualizers will automatically have the axes, and our axes management will be much smoother. 

Currently we have the following on `Visualizer`:

```python
def gca(self):
        """
        Creates axes if they don't already exist
        """
        if self.ax is None:
            self.ax = plt.gca()
        return self.ax
```

The problem is that no one is really using this or they're just calling `gca()` in draw automatically; then referencing self.ax -- so we mind as well make it a property so there isn't an extra step to avoid errors. 

This brings up a second issue; the utils library needs to be expanded. This is such a common pattern, that I have descriptors that can handle this for us (and it seems like there is going to be some good use for decorators in the future). So we need to refactor utils into a package rather than a single module. 

- [x] Refactor utils 
- [x] Add Visualizer.ax property 
- [x] Modify all the `plt.gca()` references 
- [ ] Create tests 

@rebeccabilbro -- I plan on doing this in the next sprint.

**Comment by NealHumphrey** [comment]
@bbengfort, a related (though different) issue is that it would be good to be able to set the ax after the object is instantiated. This is something I ran into in #168 - the way I structured the base MultipleVisualizer class was that you can attach multiple individual Visualizers to the MultiVisualizer instance and then use subplots to arrange them. In that case, I just used `visualizer.ax = subplot_ax` but it would be good to know that I can trust the ax to be reassigned properly if I call visualizer.ax after __init__ but before fit(). 

I think this just means that the `@ax.setter` should be responsible for re-handling anything that __init__ does with respect to the axis. 

Short term this will not be a big issue, since the MultiVisualizers will be initially designed to operate only with 'known entities', e.g. Visualizers that are specifically designed to be wrapped up into a small multiples plot. But another feature I'd be interested in working on is the concept of 'dashboards' - a series of visualizers that occur together, i.e all the ScoreVisualizers that are relevant to a classification problem could be run at once. This is related to the VisualPipelines concept - I'd like to talk to you about what you've done so far on this and how you're thinking of implementing it.

**Comment by bbengfort** [comment]
@NealHumphrey  good point; though my thought was that unless the user specified an axes at `__init__`, for the most part the initialization wouldn't actually do anything. That's where the property comes from, the `ax` wouldn't be instantiated until `draw()` (or until the getter) because in `__init__`, `self.ax = None` is the most common behavior -- which I think addresses your concern.
