### ISSUE TITLE
Visual unit tests

### ISSUE THREAD

**Issue by NealHumphrey** [DistrictDataLabs/yellowbrick#173]
As I've been developing, I find I'm working in the yellowbrick package directly but with a Jupyter notebook open to create a demo test case.  In the case of the ConfusionMatrix (pr: #144 ) I converted this into a documentation example. But for the more recent find_text_color utility (pr: #172 ), this is more of an internal tool that doesn't necessarily need a documentation example - but visual verification of its performance is a critical part of testing it behaves as expected.  Finally, most unit tests currently run through creating a visualizer (to make sure there are no errors) but don't call the final poof(). 

Questions for discussion:
* Is /examples the right place to put things like the find_text_color demo?
* Would it be useful for unit tests to output their plots to a log folder in pdf or png format for optional visual inspection? This would probably just be done when prepping for release of a new version - a quick visual scan to make sure all the created plots look reasonable. 
* Would it be a good idea to convert the /examples folder structure to instead mimic the yellowbrick package structure, and encourage each ipynb to display use of just one feature? These can then be turned into individual documentation pages (kind of [like Matplotlib](http://matplotlib.org/examples/index.html) There could also be an 'other' folder of some type that demos integrating visualizers or doing other things that don't fit into the package structure.

**Comment by bbengfort** [comment]
Ok - these are excellent questions and are _vital_ for discussion. I've tried many things to create automatic tests, but we have some workflow right now that I'd like to point out:

1. Create a folder with your GitHub username in examples/ and place all your development and working notebooks there. This way we get notebooks committed with experiments and crazy stuff, as well as development code and documentation without the overhead of managing (or trying to merge) notebooks. It also creates a bit of a gallery which is nice. 
2. Eventually, the "final" examples should go in examples/examples.ipynb or another notebook created specifically for the purpose. Management of these notebooks should be done with care since it's impossible to manage an ipynb. In your case, the find_text_color example would probably go well in `examples/palettes.ipynb`. 

I think these two things address your first bullet point. Bullet point 3 is an interesting idea - maybe one we could explore or discuss -- but we kind of already went the route of the examples structure, so let's look at alternatives. Perhaps we can make notebooks part of the documentation build process? 

As for bullet 2 - man, have I tried various things. The first issue (that we still intermittently experience) is continuous integration with Travis-CI. This is critical for the open source dev path. So the tests can't break travis, and part of that is to use the 'Agg' backend in matplotlib. 

So for example, one thing I was going to do was to test the pixels of the rendered image and make sure that it wasn't blank, but  I can't do that with 'Agg'. 

However, saving images to a log is a good idea, and I agree we should do that and slightly more than just make sure exceptions happen. Maybe we can have a conversation on Wednesday to see if we can come up with some strategies.

**Comment by NealHumphrey** [comment]
It'd be good to discuss a bit. This is mixing two topics a bit - documentation and testing. 

Just with respect to notebooks in general - breaking ipynb's down into very small chunks (i.e. one notebook per visualizer or function), instead of putting all examples into examples.ipynb, would make a big difference in avoiding merge conflicts - you'll still need to manage it with care, but not much more than you have to manage the fact that two people shouldn't be making major changes to a particular visualizer anyways, for logical (rather than physical) merge conflicts. 

It's certainly no problem to keep having people start with their notebooks in their own folder; then, you can add an additional layer of 'merge conflict management' by moving a notebook out into the root structure only when it's finished - and having only designated maintainers (you and Rebecca?) do it if you want. And of course experiments and crazy stuff can stay there. But having the visualizer's creator make a well-crafted notebook as part of the pull request for adding a new visualizer it helps make sure that documentation keeps pace with development. 

I think clarifying the documentation workflow would help make sure more gets written. At a minimum, just speaking for myself, I want to write my documentation as I go - and I know I'm not going to want to write it later. If its not clear which example notebooks get turned into documentation under which circumstances, I'll probably start getting a bit lazier about making them totally presentation-ready. 

As for tests, Travis, and logging images, sounds like we'd need to do another round of investigation before we could consider any changes.

**Comment by ndanielsen** [comment]
Just thought that I'd share - not the best place to post this:

I was just poking around matplotlib's testing documentation and they have have an `image_comparison` decorator.  Seems pretty interesting and we could use it for testing purposes of the outputs after poof is called.

http://matplotlib.org/devel/testing.html#writing-an-image-comparison-test

**Comment by bbengfort** [comment]
@ndanielsen -- wow, not only is my mind blown, but I think this is _exactly_ what we needed to get visual unit tests going. Great find! I'll experiment with getting this into yellowbrick for some simple tests. Nice one!

**Comment by ndanielsen** [comment]
@bbengfort I was thinking about trying in out on the simple scatter feature visualizer

**Comment by bbengfort** [comment]
@ndanielsen just getting to all the open issue to review and saw you made a lot of commits. Did you manage to try it out? I'm hugely interested!

**Comment by ndanielsen** [comment]
I was tinkering with it, but didn't push it in. I needed to polish the
other stuff. That's the plan for tonight and tomorrow.

--------------
Nathan James Danielsen
http://www.linkedin.com/in/nathandanielsen

Returned Peace Corps Volunteer Senegal
202-644-3206


"Who is more to be pitied, a writer bound and gagged by policemen or
one living in perfect freedom who has nothing more to say?" - Kurt
Vonnegut Jr

On Mon, May 1, 2017 at 11:09 AM, Benjamin Bengfort <notifications@github.com

**Comment by bbengfort** [comment]
Check and see if Caswell is going to be at PyCon and see if he can provide advice/huddle.

**Comment by ndanielsen** [comment]
Would be helpful, can't get the @image_comparison to recognize tests. Seems to be an issue for other devs out there.

**Comment by bbengfort** [comment]
@ndanielsen -- good to close this issue now that you won all the things?
