### ISSUE TITLE
Add pandas as a testing dependency

### ISSUE THREAD

**Issue by ndanielsen** [DistrictDataLabs/yellowbrick#178]
As we assume that users will be passing in panda dataframes to the visualizers,  so we should test against that.

**Comment by bbengfort** [comment]
Good idea -- I don't want pandas to be a dependency of yellowbrick, but we can certainly make it a testing dependency. It's interesting, Scikit-Learn doesn't really test data frames, but I don't think we can get away with not testing data frames.

**Comment by NealHumphrey** [comment]
This is something we maybe should have covered in the API section yesterday. Do we want all visualizers to be able to accept a dataframe for X and y? Sounds like yes.

**Comment by rebeccabilbro** [comment]
Added to topics for discussion for next sprint review/planning meeting.

**Comment by bbengfort** [comment]
I think we can state this more clearly as - any input that a Scikit-Learn estimator accepts, Yellowbrick Visualizers/Transformers should also accept (within context) 

For example, text transformers in Scikit-Learn can take a list of paths to load documents from, text visualizers should also be able to accept this input. 

Back on topic - I believe (or at least haven't run into problems anywhere) that Scikit-Learn estimators can easily take a DataFrame, a Series, a list, or a Numpy array. DataFrames have an `as_matrix()` method, that I believe Scikit-Learn calls.

**Comment by ndanielsen** [comment]
Just reading the matplotlib 1.5 release notes, they support plotting dataframes and anything with  __getitem__:

http://matplotlib.org/users/prev_whats_new/whats_new_1.5.html#working-with-labeled-data-like-pandas-dataframes

**Comment by bbengfort** [comment]
@ndanielsen we have moved toward using `@skipIf` for missing dependencies, there are a number of dependencies such as nltk and different versions of matplotlib that meet this requirement. I'm thinking of adding a requirements.txt to the tests directory so that developers can install all the optional packages so that no tests skip. The question of course is continuous integration, and I'm worried that trying to install pandas on travis will cause further issues. 

Will `skipIf` and a tests requirements.txt be sufficient to close this issue?

**Comment by ndanielsen** [comment]
@bbengfort I'm find with the skipIf logic and tests requirements.txt, I agree that adding pandas to travis might cause a headache but we might want to consider this further down the road.

Good to close this out
