### ISSUE TITLE
add to related packages in sklearn, move upstream?

### ISSUE THREAD

**Issue by amueller** [DistrictDataLabs/yellowbrick#193]
Hey.
This looks awesome. I've been on a quest to include more visualization directly in sklearn but haven't really gotten around to it yet (see https://github.com/scikit-learn/scikit-learn/issues/7116). I'll make a big push this summer and I'd love to see what parts of this we could upstream - people seem to keep reinventing this, see https://github.com/reiinakano/scikit-plot

lmk what you think. This project seems great and I don't want to slow it down but I also like to have standard tools for these plots in sklearn.

**Comment by bbengfort** [comment]
Glad you got a chance to check out our project, thanks for mentioning us in the Scikit-Learn issue. We very much believe that visual diagnostics is critical to machine learning, and we're glad that Scikit-Learn has so many visualizations in its examples and documentation!  We have seen scikit-plot and are interested where it goes; though I'm not sure it's so much reinventing as an important technique being advented in multiple places simultaneously due to need. We've given several talks at Data Day Seattle, PyCon, and PyData  about visual diagnostics and machine-learning specific visualization and we're glad that it's getting some attention. 

Our approach centers around the ideal of a `Visualizer` - an estimator that learns from data to produce visualizations rather than transform data or make predictions on it. Our primary goal is to integrate cleanly and smoothly with the Scikit-Learn API and Pipelines, and produce as many visualizations as possible. Many of the plots mentioned in the issue you forwarded are implemented or under development in Yellowbrick. We definitely hope to be the standard tool for this type of work. 

We'll definitely add ourselves to related packages in sklearn, and we'd be happy to have a discussion about moving upstream. We also know how difficult it is to add dependencies like matplotlib, so we're also happy to remain independent. We'll be attending PyData London and PyCon this year; perhaps we could get a group of people together to discuss possibilities?

**Comment by amueller** [comment]
Thanks for your explanation. I need to look into your approach in more detail (if I find the time :-/) We decided to add matplotlib as an optional dependency for a new "plot" submodule.

You are probably moving much faster than sklearn (which is generally pretty conservative these days), so I'm not entirely sure what the best way would be to collaborate. I want to get as much into scikit-learn as feasible this summer, and might end up upstreaming some of your work. I have to see if your interfaces are the kinds we want. You might have thought about that more than me, so I'll check out your docs.
I won't make it to pycon or PyData London, but I think @jakevdp will be at PyCon and Maybe @ogrisel at PyData London?

**Comment by amueller** [comment]
Can you maybe explain the idea behind the ``fit/transform`` interface for plotting?
What do fit and transform do for a parallel coordinate plot? From the code it looks like they just return ``self`` and ``X`` respectively.

I'm also not sure this is a good interface:
```python
# Instantiate the linear model and visualizer 
lasso = Lasso()
visualizer = PredictionError(lasso)

visualizer.fit(X_train, y_train)  # Fit the training data to the visualizer
visualizer.score(X_test, y_test)  # Evaluate the model on the test data 
g = visualizer.poof()             # Draw/show/poof the data
```
This requires deciding on the visualization before building the model.
Let's say you see something interesting and want to see a different visualization to investigate. Do you have to refit the model?

I would find it more natural to provide fitted estimator to the visualizer, and not have a ``fit`` method.
Can you give an example where that would not work? I guess it's when you're using a visual tool that requires refitting a model multiple times, but I think that's rather uncommon, isn't it?

What's the killer application that makes having an estimator interface better than just using functions?

**Comment by jakevdp** [comment]
Yep, I'll be at PyCon for a couple days, though I don't think I can stick around for the sprints.

**Comment by rebeccabilbro** [comment]
Thanks for checking it out @amueller!  I've submitted a [PR to add yellowbrick to the sklearn related projects](https://github.com/scikit-learn/scikit-learn/pull/8733).

**Comment by amueller** [comment]
Thanks @rebeccabilbro. Should I open a new issue with my API questions?

**Comment by NealHumphrey** [comment]
@amueller - @bbengfort can elaborate more on the API,  but one thing we are working on doing consistently is allowing the user to pass either a fitted or unfitted model into any visualizer. So in the example you cited, if `lasso` had previously been fitted, the user could omit the `visualizer.fit()` line and jump straight to `.score()`. This option a) needs to be better documented in the docs and b) is not 100% implemented (we need to make sure all the relevant visualizers can actually do it, there might be a few that do logic in the fit() method from before making this functionality). 

The idea for having the fit method is to allow the Visualizers to go into a visual pipeline, which @bbengfort has done some scoping work on but has not been implemented. @bbengfort anything more you can add on the API logic?

**Comment by bbengfort** [comment]
@jakevdp are you willing to get together sometime during PyCon to discuss Yellowbrick?

**Comment by bbengfort** [comment]
@amueller on the API, you're more than welcome to open up a new issue. However, @NealHumphrey is completely correct. We will ensure that visualizers can accept _both_ fitted and unfitted models. We're not 100% of the way there on that yet. 

Ideally, we'd like to create a `VisualPipeline` object that will allow us to combine multiple transformers, visualizers, and an estimator together. Neal mentioned `ParallelCoordinates`, potentially you want a pipeline that creates both `ParallelCoordinates` and a `Rank2D` matrix, and you would use a visual pipeline to do that. 

What we're not sure about is how to stack multiple `ModelVisualizer` objects on top of each other. Ideally it would be something like this:

```python
model = VisualPipeline([
    ('pcoords', ParallelCoordinates()), 
    ('rank2d', Rank2D()), 
    ('pca', PCA()), 
    ('vect', DictVectorizer()), 
    ('clf', LogisticRegression()), 
    ('report', ClassifierReport()), 
    ('confusion', ConfusionMatrix()), 
])
```
But obviously `Pipeline` objects must end in an estimator, not a transformer. We're working on a structure like `FeatureUnion` that might help us with this effort.

**Comment by amueller** [comment]
Pipelines can end in arbitrary estimators, but they can transform on all
but the last step.
The pipeline would work if you put the logreg in a voting classifier.
I'm not sure I entirely get the concept of the pipeline. As the later steps
are independent of the visualization, all that you're saying is "if I call
fit, also plot the data".
Can you explain a use case for that?
The pipeline is mostly useful inside cross validation and grid search. But
I don't see how visualization inside cross validation would be helpful.
I guess it makes sense if you repeatedly want to apply the same
visualization and models to different data sets but I'm not sure how common
that is.

Can you give an example of code that would be much simplified with the
pipeline compared to simple plotting functions?

Sent from phone. Please excuse spelling and brevity.


On Apr 12, 2017 15:59, "Benjamin Bengfort" <notifications@github.com> wrote:

@amueller <https://github.com/amueller> on the API, you're more than
welcome to open up a new issue. However, @NealHumphrey
<https://github.com/NealHumphrey> is completely correct. We will ensure
that visualizers can accept *both* fitted and unfitted models. We're not
100% of the way there on that yet.

Ideally, we'd like to create a VisualPipeline object that will allow us to
combine multiple transformers, visualizers, and an estimator together. Neal
mentioned ParallelCoordinates, potentially you want a pipeline that creates
both ParallelCoordinates and a Rank2D matrix, and you would use a visual
pipeline to do that.

What we're not sure about is how to stack multiple ModelVisualizer objects
on top of each other. Ideally it would be something like this:

model = VisualPipeline([
    ('pcoords', ParallelCoordinates()),
    ('rank2d', Rank2D()),
    ('pca', PCA()),
    ('vect', DictVectorizer()),
    ('clf', LogisticRegression()),
    ('report', ClassifierReport()),
    ('confusion', ConfusionMatrix()),
])

But obviously Pipeline objects must end in an estimator, not a transformer.
We're working on a structure like FeatureUnion that might help us with this
effort.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/DistrictDataLabs/yellowbrick/issues/193#issuecomment-293690321>,
or mute the thread

**Comment by bbengfort** [comment]
Very good point about the voting classifier - we were hoping to do something similar, but for visualizers (since they aren't actually classifiers). Visualizers hook in at fit, transform, and score (so far) and when `poof()` is called, it needs to be called on all visualizers in the pipeline. 

I agree that pipelines are useful inside cross-validation and grid search (and I think you're really close to our proposed workflow), but they're also useful in operationalization since input is usually specified by the application, not the model. Far more often than not, model selection work happens in a pipeline and our proposal is visual steering and diagnostics for model selection and operationalization. I'll get into that more in a second, however I did want to mention that we also have simple plotting functions that wrap the Visualizers for folks that don't need pipeline functionality, e.g. [classifier_report](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/classifier.py#L446). 

Our view of the workflow involves the [model selection triple](http://cseweb.ucsd.edu/~arunkk/vision/SIGMODRecord15.pdf); essentially a human driven search of a combination of features, algorithm, and hyperparameters. We believe that Scikit-Learn is ideally suited for this because Scikit-Learn's API is essentially a domain-specific language for machine learning. Yellowbrick implements steering of the search process by providing intuitive visual descriptions of each factor in the triple and fitting into the DSL natively. So to your point, the visualizers are not just operating on different data; they're operating in the data space, the feature space, the model space, the hyperparameter space, as well as operating on live data as the model is being used. 

As we get farther, we'd like to start to incorporate some of matplotlib's interactive notebook functionality to go beyond just static images, but allow the user to adjust parameters and algorithms and influence the visualizations in a more intuitive fashion. 

Ok, this comment is getting long, sorry about that; does that help explain our thinking a bit more?

**Comment by amueller** [comment]
Yeah it does give me a better idea, I'd still like to see a code example showing how the pipeline / visualizer interface helps - even a mock-up of what you envision it to be like once more fleshed out.

**Comment by bbengfort** [comment]
Perhaps this will help:

https://www.slideshare.net/BenjaminBengfort/visualizing-model-selection-with-scikityellowbrick-an-introduction-to-developing-visualizers

Starting around slide 16.

**Comment by bbengfort** [comment]
Happy to revisit this question - but closing the issue since it's been around for more than a year.
