### ISSUE TITLE
Review Docstrings for Joint Plot

### ISSUE THREAD

**Issue by jkeung** [DistrictDataLabs/yellowbrick#201]
joint_args is a dict in the JointPlotVisualizer class, in the docstrings, we need to double check if the Property and Description render correctly

**Comment by bbengfort** [comment]
Well, step one is to update the documentation to include the joint plot, it's not there yet!

**Comment by bbengfort** [comment]
So the answer is no, not really. 

<img width="692" alt="screenshot 2017-04-20 11 36 09" src="https://cloud.githubusercontent.com/assets/745966/25239289/9b64d5ae-25bd-11e7-929e-c710c3af36b4.png">

**Comment by bbengfort** [comment]
@pdamodaran would you mind taking a look? Here is the link to the rendered docs:

http://www.scikit-yb.org/en/develop/api/yellowbrick.features.html#module-yellowbrick.features.jointplot

**Comment by pdamodaran** [comment]
Sure, will do.

**Comment by pdamodaran** [comment]
@bbengfort , @jkeung 

The documentation for jointplot is in the updated docs.  The only issue is that all comments appear in a single line without carriage returns or indentation.  Is there a way to have them render the same way as they appear in the code?

**Comment by bbengfort** [comment]
@pdamodaran the rendering is [reStructuredText](http://docutils.sourceforge.net/docs/user/rst/quickref.html), which means that the docstring in the code needs to be marked up as though it's rst. There is certainly a way to do this, though I'm no expert at rst. 

Can you use the [online editor](http://rst.ninjs.org/) to see if you can get the docstring to render correctly?

**Comment by pdamodaran** [comment]
@bbengfort I have pushed the changes to the master branch of my repo.  I believe the changes I made addresses the indentation and paragraph issues.  What is the next step to test this in the documentation?

**Comment by rebeccabilbro** [comment]
@pdamodaran - want to try running the documentation build locally on your machine to see how the results render?

```
cd docs
make html
open _build/html/index.html
```

**Comment by pdamodaran** [comment]
@rebeccabilbro - I tried running the make html command and ran into the following error:
Exception occurred:
  File "/Users/Copper/Git/yellowbrick/yellowbrick/bestfit.py", line 22, in <module>
from sklearn import linear_model
ImportError: No module named sklearn

**Comment by bbengfort** [comment]
@pdamodaran are you running the documentation build in a virtual environment? I assume not, since that can be tricky with matplotlib; but it looks like you need to pip install scikit-learn to build the documentation.

**Comment by pdamodaran** [comment]
I tried scikit-learn and I got a message indicating that the requirement was already satisfied.  I also tried installing the python3 version and I still got the same error.  I had also tried in a virtual environment but ran into issues.  Is there anything else I can try?

**Comment by pdamodaran** [comment]
Here is the stack trace:

Exception occurred:
  File "/Users/Copper/Git/yellowbrick/yellowbrick/bestfit.py", line 22, in <module>
    from sklearn import linear_model
ImportError: No module named sklearn
The full traceback has been saved in /var/folders/2g/08224dlj455fs3tvmdqw0qr00000gn/T/sphinx-err-Iyklx2.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at <http://groups.google.com/group/sphinx-users/>,
or report them in the tracker at <http://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [html] Error 1

**Comment by bbengfort** [comment]
@pdamodaran can you do the following and let me know what you get?

```
$ which sphinx-build 
$ $(which sphinx-build)
```
I'm looking for the version of python that sphinx-build is using, specified at the top, something like `#!/usr/local/opt/python3/bin/python3.6`  (are you on Windows?) 

You can then run that python and try to import sklearn; see if the problem is there, or change sphinx-build to use a different version of Python on your system.

**Comment by bbengfort** [comment]
@pdamodaran so I'm working on the joint plot visualizer and it looks like the primary issue is that you were using tabs instead of spaces. Sphinx and PEP8 both would prefer if you used 4 spaces, I'll fix the document up and hopefully that solves the problem.

**Comment by bbengfort** [comment]
Ok, fixed the `JointPlot` documentation with tables:

![screenshot 2017-05-04 15 00 39](https://cloud.githubusercontent.com/assets/745966/25720356/a041aa2a-30da-11e7-823f-c011f3d352fd.png)

**Comment by pdamodaran** [comment]
Thanks @bbengfort.  I will keep that in mind next time.
