### ISSUE TITLE
Update Documentation: Load Datasets for Example Code

### ISSUE THREAD

**Issue by ndanielsen** [DistrictDataLabs/yellowbrick#223]
This is a follow issue after: https://github.com/DistrictDataLabs/yellowbrick/issues/219 is completed

The documentation section titled [Load Datasets for Example Code](http://www.scikit-yb.org/en/develop/examples/methods.html#load-datasets-for-example-code) is a bit confusing at the moment. 

After #219 is completed, this section and subsequent code examples utilizing yb data set should be updated.

As temporary solution for this, we could have the examples directly request from a source:
`data = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.data")`

**Comment by bbengfort** [comment]
Yeh, that's primarily a feature of the dump from the notebook to rst. In #209 we're going to break up the examples documentation into meaningful splits and we can handle the data loading on a per-section basis. 

For URLs for `pd.read_csv` -- we have our datasets hosted on S3. Part of what the downloader in both the examples and the tests does is check signatures; so that will go into #219. In the meantime you could use the URLs there or shorten them with bit.ly or something.

**Comment by bbengfort** [comment]
The [loading datasets for example code](http://www.scikit-yb.org/en/latest/api/datasets.html) documentation has been updated as follows:

1. Created a download module in yellowbrick 
2. Users can download datasets via `python -m yellowbrick.download` 
3. These datasets are downloaded to a `data` directory in the current working directory 
4. All examples, e.g. `pd.read_csv` assume data has been downloaded to `data/[dataset folder]` in the cwd.
