### ISSUE TITLE
Cheatsheet

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#226]
Make a PyCon style cheatsheet for yellowbrick and send it to Van de Ven.

**Comment by bbengfort** [comment]
I've completely forgotten what this was about.

**Comment by rebeccabilbro** [comment]
Here's a reminder of what we initially had in mind:

![img_1504 2](https://user-images.githubusercontent.com/8760385/43217205-f76a0ff6-900e-11e8-9971-60dcfeaf52a5.JPG)

Going to re-open this one, since I think this is still a nice-to-have.

**Comment by navarretedaniel** [comment]
As a coding novice, I enjoy a handy cheat sheet from time to time and I think it'd be great to have a cheat sheet coincide with the release of Yellowbrick v1.0.  

I started the attached mock-up by focusing on the very basics (and didn't get too deep into the substance when constrained to a single page). 

To that end:
- What aspects or features of Yellowbrick do you all believe should be emphasized (either replacing what's currently on page 1, or to be added to page 2)?  
- What is the target audience?
- Are there any stylistic preferences that you'd like to see incorporated (the mock-up was created with the power -and limitations- of MS Word)?

![Draft Yellowbrick Cheat Sheet](https://user-images.githubusercontent.com/18538131/54066089-6729d380-41f8-11e9-8996-72eb05d0bba7.png)

[Draft Yellowbrick Cheat Sheet.pdf](https://github.com/DistrictDataLabs/yellowbrick/files/2948060/Draft.Yellowbrick.Cheat.Sheet.pdf)

**Comment by pdamodaran** [comment]
@navarretedaniel - Thank you so much for putting together this cheatsheet!  This is a great start!  I like the formatting of the document and how you organized everything.  For now, my suggestions are as follows:

1) Remove the numbers from the heading.  Since the topics are not necessarily chronological, I think the numbering might be misleading.
2) I like the idea of adding an example per category.
3) To answer your question about the target audience - I believe that it will vary - we get both beginners and experienced users.  I think your cheatsheet is a good way to get people introduced to Yellowbrick.  People who want more then can go to our documentation to get further details.
4) I think in addition to adding the different types of features, we have some customization options that would be good to be included.  I will let the others weigh in on this as I am not as familiar with them.

**Comment by bbengfort** [comment]
@navarretedaniel this is wonderful! I love it and I hope you will provide it to both the Summer and Fall cohorts in Visual Analytics! 

I think that @pdamodaran's feedback is spot on. Since you're a TA, perhaps it would be easiest to focus on students of the data science program to be the primary audience? 

Stylistically, I'm happy to get you some of the YB assets and logos if you'd like to use them. We do have a color palette as well (we are a visualization library after all ;-) )

As for moving forward past Word -- how would you feel about doing this using Google Draw or draw.io? We could then share it in Google Drive with everyone. If you're not comfortable with these tools, I'm happy for other suggestions though. 

I'm really looking forward to seeing a print version of this!

**Comment by navarretedaniel** [comment]
Thank you @pdamodaran and @bbengfort for the feedback.

I'll look into both Google Draw and draw.io.  Feel free to link to the preferred YB assets/logos/palette (either here or via Slack). 

I'll also work with @lwgray to brainstorm the first version ahead of PyCon.

**Comment by bbengfort** [comment]
Perhaps you could work with @mchestnut91 as well!

**Comment by bbengfort** [comment]
The palette is here: https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/style/palettes.py#L57

**Comment by mchestnut91** [comment]
Hey @navarretedaniel, happy to connect whenever you are able to discuss how I can help as well!

**Comment by bbengfort** [comment]
@navarretedaniel now that we have the cheatsheets, I'm going to go ahead and close this issue. Thank you for your hard work! If you'd like to do a v2 cheatsheet we can create a new issue for it.
