### ISSUE TITLE
Lines in Classification Report 

### ISSUE THREAD

**Issue by cgivre** [DistrictDataLabs/yellowbrick#267]
First, this is an awesome module!!
I created a classification report (see attached) and the white lines make reading the numbers impossible.
![unknown](https://user-images.githubusercontent.com/5513150/27615699-2978e55c-5b78-11e7-9ceb-d63026f18778.png)
I wanted to ask if there is a way to either lighten or remove these lines so that you can read the various scores?
Thanks!

**Comment by bbengfort** [comment]
@cgivre thanks for the note, and for using Yellowbrick! You're right the numbers are tough to read with those lines, we'll definitely have to explore a fix on our end. Perhaps we can add a box behind the text with some opacity that makes it easier to read. I know that we did do a dark/light text algorithm so that we had white text on a dark background and vice versa. Hopefully we can use that to make things more readable. 

In the meantime you can get access to the gridlines through the `ax` property of the visualizer, and modify the color yourself:

```python
model = ClassificationReport(RandomForestClassifier())
model.fit(X_train, y_train)
model.score(X_test, y_test)

model.ax.grid(color="#666666", linestyle='--')

model.poof()
```

Which results in something like:

![occupancy](https://user-images.githubusercontent.com/745966/27749328-1fc25090-5da1-11e7-9c8f-794c8b9a8936.png)

**Comment by ianozsvald** [comment]
When I've done these sort of plots in the past I've always wondered if I could move the grid lines to be _between_ the grid items to form box-edges, rather than running through the centre of the cells. This would turn the display into discrete cells. Might that be worth exploring?

**Comment by bbengfort** [comment]
Definitely worth exploring, but not 100% sure how to. @NealHumphrey -- you were taking a look at using the `pcolormeshgrid` instead of `imshow`, is it possible with this method?

**Comment by NealHumphrey** [comment]
@bbengfort and @ianozsvald - yes, it should be the default result if the classification report is converted to a `pcolormeshgrid`. You can see that the lines are outside the grids on the confusion matrix in these screenshots: https://github.com/DistrictDataLabs/yellowbrick/pull/144

**Comment by bbengfort** [comment]
Updated in #348 -- classification report now looks like this:

![classification_report](https://user-images.githubusercontent.com/745966/37571521-084cd0a6-2ad4-11e8-8805-ff42828430c2.png)

@cgivre @ianozsvald -- this will be part of the upcoming v0.6 release of yellowbrick; thank you so much for your patience!

**Comment by ianozsvald** [comment]
Brilliant :-) Looking forward to it.

**Comment by bbengfort** [comment]
@ianozsvald released late last night!
