### ISSUE TITLE
Plot multiple visualizations without retraining of model.

### ISSUE THREAD

**Issue by wiseyoungbuck** [DistrictDataLabs/yellowbrick#296]
Is there a way to do this? If so, is it in the documentation? I haven't been able to find an example or reference in the docs.

**Comment by bbengfort** [comment]
We're still working on a clearer solution to this using `VisualPipelines` -- which will allow multiple visualizers to be fit and drawn one at a time. We're having some challenges inside of notebooks with this, so it isn't quite ready yet, but hopefully, in an upcoming version it will be very clear how to do this. 

Until then, you can certainly pass a fitted model to a `ModelVisualizer` and draw the visualization using `score()` or `draw()` rather than calling `fit()` to achieve the same thing. Here is an example:

```python
import pandas as pd 
import matplotlib.pyplot as plt 

from sklearn.linear_model import LassoCV 
from sklearn.model_selection import train_test_split as tts 

from yellowbrick.regressor import PredictionError, ResidualsPlot, AlphaSelection 

data = pd.read_csv('examples/data/concrete/concrete.csv') 
feature_names = ['cement', 'slag', 'ash', 'water', 'splast', 'coarse', 'fine', 'age']
target_name = 'strength'

X = data[feature_names].as_matrix() 
y = data[target_name].as_matrix() 

X_train, X_test, y_train, y_test = tts(X, y, test_size=0.2) 


# Create fitted model 
model = LassoCV()
model.fit(X_train, y_train) 

# Alpha selection with fitted model 
alphas = AlphaSelection(model) 
alphas.draw() 
alphas.poof()

# Prediction error plot 
pe = PredictionError(model)
pe.score(X_test, y_test) 
pe.poof()

# Residuals plot 
residuals = ResidualsPlot(model)
residuals.score(X_train, y_train, train=True) 
residuals.score(X_test, y_test, test=True)
residuals.poof()
``` 

We do fully intend to support passing either fitted or unfitted models to `ModelVisualizers`, I will create an issue so that in the next update we can ensure that we don't call fit multiple times.

**Comment by bbengfort** [comment]
See #297

**Comment by wiseyoungbuck** [comment]
Thanks for the prompt response. I'm looking forward to the new pipelines.
