### ISSUE TITLE
Check if an estimator is fitted and visualize without modification

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#297]
Don't call fit on an already fitted estimator.

`ModelVisualizer` objects should be able to accept either a fitted or unfitted model; we shouldn't call fit on the model if it's already fitted, especially if `fit()` is a hook for drawing. 

Moreover there are a series of visualizers that use `fit()` to draw themselves but only need information from the model, there should be a shortcut function for drawing these things (unless they need data).

**Comment by dylanking42** [comment]
Is this related to the sklearn.utils.validcation.check_is_fitted?
http://scikit-learn.org/stable/modules/generated/sklearn.utils.validation.check_is_fitted.html

SO discussion on related topic:
https://stackoverflow.com/questions/39884009/whats-the-best-way-to-test-whether-an-sklearn-model-has-been-fitted

check is fitted will raise an error if a model IS NOT fitted, but maybe it could be use to bypass fit() within ModelVisualizer?

**Comment by bbengfort** [comment]
@dylanking42 that's a great idea - I think `check_is_fitted` is exactly what we need for this! Did you want to submit a PR that fixes this?

**Comment by dylanking42** [comment]
If I knew how I would have already done it -_-

**Comment by bbengfort** [comment]
Totally understood, no worries! The links and notes are very helpful!

**Comment by bbengfort** [comment]
The check fitted method requires params to be known in advance. We can have visualizers specify those params using an internal `_is_fitted` or `fit_params` mechanism. We should also capture `sklearn.exceptions.NotFittedError` and raise `yellowbrick.exceptions.NotFitted` instead. 

Here is some sample utility code from a previous project (though this needs to be refined a lot:

```
import sklearn 
import warnings 
from sklearn.utils.validation import check_is_fitted

def is_fitted(estimator):
    if hasattr(estimator, '_is_fitted'):
         return estimator._is_fitted() 

    warnings.warn("performing a broad search of fit params", UserWarning) 
    try:
         check_is_fitted(estimator, ["coef_", "estimator_"], all_or_any="any")
         return True 
    except sklearn.exceptions.NotFittedError:
          return False 
```

**Comment by bbengfort** [comment]
This is also related to quick methods which would benefit from being able to draw an already fitted model without having to pass train-test splits directly into the method.

**Comment by amueller** [comment]
There's two easy ways to see if you need to fit. The more obvious and easier is to just call ``predict`` or ``predict_proba`` or whatever you need, and if a ``NotFittedError`` is thrown, you fit.

The second one is to check if any attribute with a trailing underscore exists. But there's really no reason why you should reimplement this logic, we have the ``NotFittedError`` exactly for this usecase.

**Comment by rebeccabilbro** [comment]
Awesome, thanks @amueller &mdash; this will be super helpful for our roadmap planning (happening later this month). Stay tuned!

**Comment by FeFortti** [comment]
Has this problem been solved?

In my case, I already have a model with optimized hyperparameters and trained with a training database, and now I would just like to choose the best threshold for this already trained model, but using data from an independent validation database. Is this possible to do using DiscriminationThreshold()? The goal is only to visualize the metrics, considering the previously trained model and validation data from an independent database, **without any modification (re-training) o**f the model. And, from this visualization, define the best threshold, based on one (or more) of the calculated metrics.

**Comment by bbengfort** [comment]
Hello @FeFortti -- yes, this problem has indeed been solved :-); if the model has an `is_fitted` parameter, you can set that to `True` and when you call `fit()` the model should ignore overwriting the model. Another option is to use the [PrePredict](https://scikit-yb.org/en/latest/api/contrib/prepredict.html) estimator; here you just pass in `y` and `yhat` from your database and set any required learned parameters (e.g. parameters on the model ending in `_`) and the `fit()` method is a no-op. 

The `DiscriminationThreshold` does indeed have `is_fitted` so you can pass that as `True` and hopefully that will help you with your metrics!

https://www.scikit-yb.org/en/latest/api/classifier/threshold.html#module-yellowbrick.classifier.threshold

> Has this problem been solved?
> 
> In my case, I already have a model with optimized hyperparameters and trained with a training database, and now I would just like to choose the best threshold for this already trained model, but using data from an independent validation database. Is this possible to do using DiscriminationThreshold()? The goal is only to visualize the metrics, considering the previously trained model and validation data from an independent database, **without any modification (re-training) o**f the model. And, from this visualization, define the best threshold, based on one (or more) of the calculated metrics.

**Comment by FeFortti** [comment]
Hi @bbengfort 

Perfect! Thank you very much for the quick and detailed response!

One last question: Even if I call the **.fit() method** for the viewer **with this independent validation data**, there will be no modification (retraining) of the model provided to the viewer, right?

Below I provide the code I am using, so that it is clearer and I can confirm the practical application of this question.

`#Training the tune model with train data
rf = RandomForestClassifier(...definition of optimized hyperparameters... , random_state=42)
rf.fit(X_train, y_train)

#Calculating the best discriminant threshold for f-score with validation indepedent data
visualizer = DiscriminationThreshold(rf, exclude="queue_rate", random_state=42)
visualizer.fit(X_val, y_val)
visualizer.poof()
argmax = visualizer.cv_scores_["fscore"].argmax()
threshold = visualizer.thresholds_[argmax]
print(f"Best threshold for F1-score: {threshold}")

# Predicting using the optimal threshold
y_pred_test_threshold = (rf.predict_proba(X_test)[:, 1] >= threshold).astype(bool)
y_pred_test_threshold = pd.DataFrame(y_pred_test_threshold)

# Calculating metrics for test data
print(f"\tRecall (sensitivity): {recall_score(y_test, y_pred_test_threshold, pos_label=1):1.3f}")
...`

**Comment by FeFortti** [comment]
Hi @bbengfort

Perfect! Thank you very much for the quick and detailed response!

One last question: Even if I call the .fit() method for the viewer with this independent validation data, there will be no modification (retraining) of the model provided to the viewer, right?

Below I provide the code I am using, so that it is clearer and I can confirm the practical application of this question.

`
#Training the tune model with train data
rf = RandomForestClassifier(...definition of optimized hyperparameters... , random_state=42)
rf.fit(X_train, y_train)

#Calculating the best discriminant threshold for f-score with validation indepedent data
visualizer = DiscriminationThreshold(rf, exclude="queue_rate", random_state=42)
visualizer.fit(X_val, y_val)
visualizer.poof()
argmax = visualizer.cv_scores_["fscore"].argmax()
threshold = visualizer.thresholds_[argmax]
print(f"Best threshold for F1-score: {threshold}")

#Predicting using the optimal threshold
y_pred_test_threshold = (rf.predict_proba(X_test)[:, 1] >= threshold).astype(bool)
y_pred_test_threshold = pd.DataFrame(y_pred_test_threshold)

#Calculating metrics for test data
print(f"\tRecall (sensitivity): {recall_score(y_test, y_pred_test_threshold, pos_label=1):1.3f}")
...
`

**Comment by FeFortti** [comment]
Hi @bbengfort

Perfect! Thank you very much for the quick and detailed response!

One last question: Even if I call the .fit() method for the viewer with this independent validation data, there will be no modification (retraining) of the model provided to the viewer, right?

Below I provide the code I am using, so that it is clearer and I can confirm the practical application of this question.

```
#Training the tune model with train data
rf = RandomForestClassifier(...definition of optimized hyperparameters... , random_state=42)
rf.fit(X_train, y_train)

#Calculating the best discriminant threshold for f-score with validation indepedent data
visualizer = DiscriminationThreshold(rf, exclude="queue_rate", random_state=42)
visualizer.fit(X_val, y_val)
visualizer.poof()
argmax = visualizer.cv_scores_["fscore"].argmax()
threshold = visualizer.thresholds_[argmax]
print(f"Best threshold for F1-score: {threshold}")

#Predicting using the optimal threshold
y_pred_test_threshold = (rf.predict_proba(X_test)[:, 1] >= threshold).astype(bool)
y_pred_test_threshold = pd.DataFrame(y_pred_test_threshold)

#Calculating metrics for test data
print(f"\tRecall (sensitivity): {recall_score(y_test, y_pred_test_threshold, pos_label=1):1.3f}")
...
```

**Comment by FeFortti** [comment]
Hi @bbengfort

Perfect! Thank you very much for the quick and detailed response!

One last question: Even if I call the .fit() method for the viewer with this independent validation data, there will be no modification (retraining) of the model provided to the viewer, right?

Below I provide the code I am using, so that it is clearer and I can confirm the practical application of this question.

```
# Training the tune model with train data
rf = RandomForestClassifier(...definition of optimized hyperparameters... , random_state=42)
rf.fit(X_train, y_train)

# Calculating the best discriminant threshold for f-score with validation indepedent data
visualizer = DiscriminationThreshold(rf, exclude="queue_rate", random_state=42)
visualizer.fit(X_val, y_val)
visualizer.poof()
argmax = visualizer.cv_scores_["fscore"].argmax()
threshold = visualizer.thresholds_[argmax]
print(f"Best threshold for F1-score: {threshold}")

# Predicting using the optimal threshold
y_pred_test_threshold = (rf.predict_proba(X_test)[:, 1] >= threshold).astype(bool)
y_pred_test_threshold = pd.DataFrame(y_pred_test_threshold)

# Calculating metrics for test data
print(f"\tRecall (sensitivity): {recall_score(y_test, y_pred_test_threshold, pos_label=1):1.3f}")
...
```

**Comment by FeFortti** [comment]
Hi @bbengfort

Perfect! Thank you very much for the quick and detailed response!

One last question: Even if I call the `.fit()` method for the viewer with this independent validation data, there will be no modification (retraining) of the model provided to the viewer, right?

Below I provide the code I am using, so that it is clearer and I can confirm the practical application of this question.

```python
# Training the tune model with train data
rf = RandomForestClassifier(...definition of optimized hyperparameters... , random_state=42)
rf.fit(X_train, y_train)

# Calculating the best discriminant threshold for f-score with validation indepedent data
visualizer = DiscriminationThreshold(rf, exclude="queue_rate", random_state=42)
visualizer.fit(X_val, y_val)
visualizer.poof()
argmax = visualizer.cv_scores_["fscore"].argmax()
threshold = visualizer.thresholds_[argmax]
print(f"Best threshold for F1-score: {threshold}")

# Predicting using the optimal threshold
y_pred_test_threshold = (rf.predict_proba(X_test)[:, 1] >= threshold).astype(bool)
y_pred_test_threshold = pd.DataFrame(y_pred_test_threshold)

# Calculating metrics for test data
print(f"\tRecall (sensitivity): {recall_score(y_test, y_pred_test_threshold, pos_label=1):1.3f}")
...
```

**Comment by bbengfort** [comment]
@FeFortti that's correct, even if you call `fit` so long as `is_fitted` is set to `True`, the model will not be retrained and there will be no modification.  Here are the changes to your code that are required:

```python
rf = RandomForestClassifier(...definition of optimized hyperparameters... , random_state=42)
rf.fit(X_train, y_train)

visualizer = DiscriminationThreshold(rf, exclude="queue_rate", random_state=42, is_fitted=True)
visualizer.fit(X_val, y_val)
visualizer.show()
```

Just for reference, here is the base class that performs the `is_fitted` check:

https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/base.py#L389-L391

And here is the `check_fitted` function:

https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/utils/helpers.py#L84


> Hi @bbengfort
> 
> Perfect! Thank you very much for the quick and detailed response!
> 
> One last question: Even if I call the `.fit()` method for the viewer with this independent validation data, there will be no modification (retraining) of the model provided to the viewer, right?
> 
> Below I provide the code I am using, so that it is clearer and I can confirm the practical application of this question.
> 
> ```python
> # Training the tune model with train data
> rf = RandomForestClassifier(...definition of optimized hyperparameters... , random_state=42)
> rf.fit(X_train, y_train)
> 
> # Calculating the best discriminant threshold for f-score with validation indepedent data
> visualizer = DiscriminationThreshold(rf, exclude="queue_rate", random_state=42)
> visualizer.fit(X_val, y_val)
> visualizer.poof()
> argmax = visualizer.cv_scores_["fscore"].argmax()
> threshold = visualizer.thresholds_[argmax]
> print(f"Best threshold for F1-score: {threshold}")
> 
> # Predicting using the optimal threshold
> y_pred_test_threshold = (rf.predict_proba(X_test)[:, 1] >= threshold).astype(bool)
> y_pred_test_threshold = pd.DataFrame(y_pred_test_threshold)
> 
> # Calculating metrics for test data
> print(f"\tRecall (sensitivity): {recall_score(y_test, y_pred_test_threshold, pos_label=1):1.3f}")
> ...
> ```

**Comment by FeFortti** [comment]
Hi @bbengfort 

Perfect!! Thank you very much!

In your code suggestion, in addition to suggesting the inclusion of the `is_fitted=True` argument we were discussing, you also used `.show()` instead of the option I'm using, `.poof()`. Is there a problem with using `.poof()`?

**Comment by bbengfort** [comment]
`poof()` is a deprecated method and all it does is call `show()`; I'd recommend using `show()` but you can use `poof()` if you prefer.  

> Hi @bbengfort
> 
> Perfect!! Thank you very much!
> 
> In your code suggestion, in addition to suggesting the inclusion of the `is_fitted=True` argument we were discussing, you also used `.show()` instead of the option I'm using, `.poof()`. Is there a problem with using `.poof()`?

**Comment by FeFortti** [comment]
Perfect, @bbengfort !

Thank you very much for all the detailed, complete and quick answers! It was a great help for my project!
