### ISSUE TITLE
Best fit curves

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#30]
We have linear best fit lines, but will need quadratic and exponential too.

**Comment by pvomelveny** [comment]
I started working on this one yesterday. I'll try to finish it up later today (6/6) or tomorrow.

**Comment by rebeccabilbro** [comment]
@pvomelveny awesome! I was thinking it might make most sense to make a bestfit.py module within yellowbrick that has a BestFit base object -- then we could have LinearBestFit, QuadraticBestFit, ExponentialBestFit classes inherit from the base. What do you think?

**Comment by pvomelveny** [comment]
Sorry for the delay! 

I've basically gotten a simple version working. It could be better optimized (it uses numpy's polyfit for every case) but it'll make best fit lines well enough for now (I need to brush up on my linear algebra before I feel comfortable trying to copy Seaborn's fast-fit and logx functions, but from what I can tell it's fairly basic fitting).  

I made it with being a mix-in in mind, but I'm not yet sure how to best integrate it into the API, so it's living in a sad, tortured state of un-class, where all it does is add a function to a class that you then have to call (at which point it might as well just be a standalone function?).

I need to check up on all the work you all have been doing and think about it, but I'd gladly take suggestions if someone already have an idea! Mostly just to document my own thinking:
* Where are the best places to integrate this with our other classes? 
    * Are there places we can safely assume the necessary parameters will be stored? 
* Would we rather just make it into a plain old function that we can then call wherever we need best fit lines?
    * It'll all be behind the scenes anyways, yeah? So to the average user it'll be an inconsequential decision.
* How much customization of the line do we need to offer? 
    * Right now you can choose the color, but I left the option to pass kwargs to matplotlib. This may be overkill for what it's doing.

**Comment by bbengfort** [comment]
@pvomelveny - ok, I've closed #9 which was the best fit lines; though I also added the quadratic as well. Still left to implement are Exponential and Logrithmic. 

Take a look at my implementation here: https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/bestfit.py

I kept it purposefully simple and since you said you had started the mixin class, all I did was create a simple `draw_best_fit` function that takes as input the X values, the y values and the matplotlib axes to draw on (e.g. if you're drawing on multiple subplots for a multiplot figure, this will ensure the right axes gets drawn on).  

You can specify the estimator as a string ('linear, 'quadratic', 'exponential', 'log', 'select_best') and the function will farm out the generation of the model to a fit_NAME function, where NAME is one of the strings above. The only requirement for the return object of that model is that it has a `predict` function that takes the same arguments as a Scikit-Learn estimator and returns the same output. Of these estimators only linear, quadratic, and select best are currently implemented. 

Select best uses mean square error to determine which line to use. 

All other keyword arguments are passed to the ax.plot function (e.g. color line style, line width, etc.) 

So  I hope that this addresses bullet point #3 and I've really done bullet point #2, though I haven't answered anything from your bullet point #1. 

From here, could you add your implementation to fit_exponential and fit_log and see how that works out? I'm open to other discussion as well.

**Comment by joeyzhang823** [comment]
I am working on this issue and finished adding exponential, will add log soon. I will make a pull request later this week

**Comment by lwgray** [comment]
@joeyzhang823 Thanks for looking at this...looking forward to your PR.

**Comment by PandaBoi** [comment]
Hey!
I am new to open source contribution and would like to know more about how I can start off with it for this organization, could anyone help me out with some guidance? Would like to know how issues are assigned as well. Thanks!!

**Comment by lwgray** [comment]
Hi @PandaBoi 

Thanks for reaching out to us.  We are excited that you would like to contribute to open-source projects like Yellowbrick.  However, the way that Yellowbrick is structured (we divide our development year into three  4-month semesters) we send out a call for core-contributors(person wanting to contribute to yellowbrick) at the beginning of each semester.  We are already in the summer semester and have finished signups but, we would be more than happy for you to become a core contributor during our next round of contributions.  You can sign-up below for the Fall semester.

Fall Semester Core Contributor Signup - https://forms.gle/NT3inRQhaV278kf96

**Comment by PandaBoi** [comment]
@lwgray Thanks for reaching out. Looking forward to joining in next semester!

**Comment by rebeccabilbro** [comment]
Going to go ahead and close this one out since it's gone a bit stale; to anyone with interest/bandwidth &mdash; feel free to reopen!
