### ISSUE TITLE
Wrong parameter name in docs for PCADecomposition

### ISSUE THREAD

**Issue by ccjolley** [DistrictDataLabs/yellowbrick#324]
Hi... this is a super-minor issue, but it tripped me up for a bit. The documentation for the PCADecomposition constructor (http://www.scikit-yb.org/en/latest/api/features/pca.html) has the following example:

`visualizer = PCADecomposition(scale=True, center=False, col=y)`

When I tried this in my own code, the color-coding didn't work unless I used the full name of the `color` argument, i.e.:

`visualizer = PCADecomposition(scale=True, center=False, color=y)`.

Probably easiest to just change the documentation.

**Comment by ndanielsen** [comment]
@ccjolley thanks for writing up this ticket! Super important that we get the documentation correct.

**Comment by ndanielsen** [comment]
A quick look shows that we have this incorrectly documented in two places:

https://github.com/DistrictDataLabs/yellowbrick/blob/develop/docs/api/features/pca.rst

https://github.com/DistrictDataLabs/yellowbrick/blob/c5b2346c03ba5b8aaadf6a4037b1939e9f3063a2/yellowbrick/features/pca.py#L134-L144

@ccjolley you're welcome to make a PR in with the fixes if you would like (and would get the credit for it), otherwise someone else is welcome to pick this up. 

Thanks again for flagging this!
