### ISSUE TITLE
Estimator Attributes - Naming Convention - Audit

### ISSUE THREAD

**Issue by lwgray** [DistrictDataLabs/yellowbrick#326]
Yellowbrick has adopted the sklearn naming convention regarding estimator attributes.  We have found that there is some inconsistency in our application of this naming convention.

#### What is this naming convention?
Simply, estimator attributes should be suffixed with an underscore.  

#### What is an estimator attribute?
@bbengfort states that estimator attributes should either be hyperparameters (supplied by the user and having reasonable defaults) or parameters and things that are added during fit

#### What is the Impetus for these changes?:
@bbengfort 
“there are several other visualizers that are not consistent with this behavior and need to be updated.”

@ndanielsen 
I agree that we need to make an issue, and likely conduct an audit to ensure that all visualizers are conforming to this spec for self.score_ but also for things like self.classes_

#### Good Starting point:
There are two common estimator attributes that we often use:  self.scores and self.classes

**Comment by ndanielsen** [comment]
@lwgray thanks for creating this issue. 

I think that this would be a great issue to resolve before pycon (along with some other bug fixes and general maintenance).

**Comment by bbengfort** [comment]
@lwgray is this in the audit spreadsheet by any chance?

**Comment by lwgray** [comment]
@Kautumn06 Thanks for handling this!

**Comment by rebeccabilbro** [comment]
@lwgray @Kautumn06 @bbengfort &mdash; I'm going to mark this complete since it has been added to (1) our PR review checklist in our contributors docs and (2) the spreadsheet for #669 and is being documented there. It's likely we'll end up opening follow-on tasks for visualizers or visualizer families that require updates in light of the audit, so it probably makes most sense to verify these attributes then rather than as a standalone task
