### ISSUE TITLE
Add Sphinx autodoc and intersphinx

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#33]
Add sphinx autodoc and intersphinx to pull docstrings into documentation.

**Comment by bbengfort** [comment]
Planning on moving all the documentation over to reStructuredText and Sphinx?

**Comment by lauralorenz** [comment]
Yes

**Comment by lauralorenz** [comment]
I actually assumed yall were already using sphinx; now that I'm in it I see you're actually using mkdocs which we can stick with if yall like, though I don't see anything like sphinx autodoc for autogenerated api documentation so I personally am pro sphinx in this case

**Comment by bbengfort** [comment]
I think the documentation will be extremely important, especially since it will have to contain images, example code, and a lot of details about how to work with Yellowbrick. We're taking a lot of inspiration from Seaborn; it and the pandas documentation reveal how important it is to visually and intuitively explain how to use the library. If Sphinx will help us achieve that level of documentation (after all, both Pandas and Seaborn use Sphinx) then I'm all for it.

**Comment by lauralorenz** [comment]
I would consider the scope of this one closed by #35 and the scope of implementing it more widely to be represented by open issue #36. Reopen if you think otherwise
