### ISSUE TITLE
Code Conventions Guide for Documentation and Examples

### ISSUE THREAD

**Issue by ndanielsen** [DistrictDataLabs/yellowbrick#340]
In our documentation and code examples, we have several different styles around referring to the workflow and how to format code examples.

It would be helpful to identify and establish a handful of code conventions that we follow to reduce the cognitive load for using this library.

Code Examples:
- Should always include the import path of the visualizer

**Comment by bbengfort** [comment]
This relates to #327 where I mentioned:

A more extensive overhaul of color and color handling in YB is required. We have 4 different methodologies that are mixed and matched in kind of a strange fashion. More than that, Yellowbrick-specific requirements have emerged. Briefly, they are:

- We need discrete colors that are visually separate for classes
- We need continuous colors for regression values and heatmaps

Both of these requirements are specified by the target variable. Finally, we need helpers for the other utilities we use; but those can be largely handled with resolve_colors and get_color_cycle.

**Comment by bbengfort** [comment]
If it's ok with you - I'd like to turn this issue into the issue that handles that, and part of the definition of done will be to update the documentation and create a style guide.

**Comment by ndanielsen** [comment]
@bbengfort I changed to title to more accurately reflect the intent of this issue. Instead of colors / styles / palletes, I meant to make this issue about Documentation Code Conventions:

We should have a consistent way of demonstrating how to use different visualizers. 

One example is that we should always include the import statements about where the visualizer lives in the code sample. I've heard some feedback that it when it is not present in the code sample, new users don't know how / where to find it to import it. 

ie :

Example found here: http://www.scikit-yb.org/en/latest/quickstart.html#using-yellowbrick

```
from yellowbrick.features import ParallelCoordinates

visualizer = ParallelCoordinates()
visualizer.fit_transform(X, y)
visualizer.poof()

```

Following example found here: http://www.scikit-yb.org/en/latest/api/features/pcoords.html#parallel-coordinates

```
# Instantiate the visualizer
visualizer = ParallelCoordinates(classes=classes, features=features)

visualizer.fit(X, y)      # Fit the data to the visualizer
visualizer.transform(X)   # Transform the data
visualizer.poof()         # Draw/show/poof the data

```

This is a simple example but I know that @Kautumn06 has a few more like this.

**Comment by Kautumn06** [comment]
I submitted a pull request this morning that adds the missing import statements to the individual pages in the documentation. While I did make a few edits (such as fixing typos and making "Scikit-Learn" lowercase), I tried to focus on just adding the import statements for this pull request so that it would be easier to review. However, there are two other issues about our code blocks in the documentation that I think we could improve and I would really like your feedback.

First, I think it would be helpful to add information about downloading the Yellowbrick datasets to each page. While our site does have a [datasets](http://www.scikit-yb.org/en/latest/api/datasets.html) page that explains how to download and load the datasets, it's very likely that a new user would miss it. And this will cause problems for them if they try to use the example code on a specific visualizer's page since most often the code blocks start like this:

![load_data_function](https://user-images.githubusercontent.com/19958803/37610201-5d6516c4-2b75-11e8-9eba-5ee8e21d23d6.png)

Running this code will return an error. And unless the user has read the datasets page, they won't know that it's because they need to include this code for the `load_data` function to work.

![load_data](https://user-images.githubusercontent.com/19958803/37609826-80ff82be-2b74-11e8-98a4-e58abd496efa.png)

So I'd like to find a solution that will ensure that readers will be aware of this, but that also doesn't clog up our documentation by adding large amounts of repetitive data to each of our visualizer pages.

One idea could be to rely on [scikit-learn datasets](http://scikit-learn.org/stable/datasets/index.html) for these pages since some of our documentation already does this. For example, [ClassPredictionError](http://www.scikit-yb.org/en/latest/api/classifier/class_prediction_error.html) uses `from sklearn.datasets import make_classification` and both the [Elbow Method](http://www.scikit-yb.org/en/latest/api/cluster/elbow.html) and [Silhouette Visualizer](http://www.scikit-yb.org/en/latest/api/cluster/silhouette.html) use `from sklearn.datasets import make_blobs`.  Scikit-learn also has `make_regression` and other toy datasets we could use.

Another idea could be by adding a note to each page that directs users to our datasets page if they would like to try to run the examples themselves. We have something similar on our [Walkthrough](http://www.scikit-yb.org/en/latest/quickstart.html#walkthrough) page:

![datasets_note](https://user-images.githubusercontent.com/19958803/37611281-4dbb8f84-2b78-11e8-92e9-6fed9a5b20cc.png)

So I'll just stop here before this "comment" turns into a full-fledged novella! Please let me know any questions or ideas that you have!

**Comment by bbengfort** [comment]
@Kautumn06 thanks for your thoughtfulness on the documentation, and I certainly understand where you're coming from. Perhaps what we can do is prioritize #219 -- the creation of a data module like scikit-learn, nltk, or seaborn; that way our users can recreate the code exactly with only one line of additional code.  I could probably get that done by the next time we meet. 

One thing I'm concerned about is that there is often a lot of preparation code in the examples without getting directly to the visualization -- and it happens without discussion. For the documentation, I envision something more akin to [seaborn's examples](https://seaborn.pydata.org/generated/seaborn.heatmap.html#seaborn.heatmap) where there is one example after the other with snippets and visualizations. The API pages need to be a direct and simple reference to the core of the code base and the various arguments that can manipulate Yellowbrick, scikit-learn and matplotlib. 

What I envision is the API pages outlined something like:

- Header/quick link to API reference 
- Introduction 
- Quick use/example 
- Discussion 
- How to interpret the results 
- Example 2 
- Example 3 
- Example 4 
- API Reference 

However, I also do want more discussion oriented pages like [seaborn's tutorials](https://seaborn.pydata.org/tutorial/categorical.html) -- right now we have the quick start and the model selection tutorial; but it would be great if we could go deeper with more pages that have multiple visualizers on each and walk through each step of the process from data loading and beyond. 

Also, speaking of the quick start, those visualizations should probably be updated with the latest version of YB (they're a little stale).

**Comment by ndanielsen** [comment]
I agree with the need to prioritize https://github.com/DistrictDataLabs/yellowbrick/issues/219 as it seems to repeated comment about our documentation. @Kautumn06 after your finish your next / current round of documentation edits, you're also welcome to try and tackle this one -- or not =)

**Comment by Kautumn06** [comment]
@bbengfort I think you make a really great point about the amount of preparation code that a reader must go through before actually getting to the visualizations. If it's alright, I'd like to try to tackle #219 since I think it would have a bigger impact on our documentation than some of the smaller fixes I've been working on.

**Comment by bbengfort** [comment]
@Kautumn06 absolutely - please feel free to message me on Slack as you're working through it if you have any questions or want to run anything by me.

**Comment by ndanielsen** [comment]
Other TODOs
- Add to RST stub for visualizers to help with documenting visualizers

**Comment by bbengfort** [comment]
@Kautumn06 another thing I'm noticing in the documentation that would be great for you to fix: changing single backtick inline markup to double backtick inline markup. More details:

I'm seeing the following markup:

```rst 
Yellowbrick provides the `yellowbrick.text` module for text-specific visualizers. 
The `TextVisualizer` class specifically deals ... 
```

The backtick inline markup, ``, in [Markdown means code](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code), and I think that's what we're used to writing, hence the mistake. However, in RST this renders as emphasis:

> Yellowbrick provides the _yellowbrick.text_ module for text-specific visualizers. 
> The _TextVisualizer_ class specifically deals &hellip; 

We need to change it to double back ticks:

```rst 
Yellowbrick provides the ``yellowbrick.text`` module for text-specific visualizers. 
The ``TextVisualizer`` class specifically deals ... 
```

For it to (correctly) render as code:

> Yellowbrick provides the `yellowbrick.text` module for text-specific visualizers. 
> The `TextVisualizer` class specifically deals &hellip;
