### ISSUE TITLE
Create yellowbrick.contrib and deprecate non-core visualizers

### ISSUE THREAD

**Issue by ndanielsen** [DistrictDataLabs/yellowbrick#341]
I that we should create a `yellowbrick.contrib` module to store visualizers, utilities and other functionalities  that are prototypes, works in progress or just plain experimental.

For the core of Yellowbrick, only highly stable, fully tested, high value added and well documented visualizers and etc should be allowed to pass in.

I think that the first step should be to identify visualizers that are be suited for `contrib` and add a `depreciated` warning to them with a note that they are moving to contrib.

I propose using the deprecation library to do this. It seems stable and well tested. 
http://deprecation.readthedocs.io/en/latest/ 

For initial candidate visualizers to move, I recommend:

- features.scatter.ScatterVisualizer
- classifier.boundaries.DecisionBoundariesVisualizer

For experimental utilities, I think that we can also immediately add a basic working implementation of StatsModelsWrapper(BaseEstimator) that was in https://github.com/DistrictDataLabs/yellowbrick/issues/306

**Comment by ndanielsen** [comment]
@bbengfort @rebeccabilbro @NealHumphrey any thoughts on this proposal?

**Comment by bbengfort** [comment]
Yes, I think this is the best way to move forward; we can have new contributors add to contrib, then as they become documented move them into the main library. 

I do have two questions:

- Tests? 
- Contrib documentation? 

For the first, I'm thinking we just have test files next to the actual files in contrib; but we can have pytest ignore them so they're not part of CI (pytest will run them on demand). 

For the second, I suggest we put a contrib section in the main docs that just does an API read of the docstrings rather than having full blown documentation. 

Thoughts?

**Comment by bbengfort** [comment]
Also for us, we can add visualizers directly to the main code base, but it is expected we will test and document them; and if we want to do something prototype-y we can put it in contrib; only brand new contributors are expected to add to contrib until after their first PR?

**Comment by ndanielsen** [comment]
I agree with the contrib documentation suggestion. For testing of contrib, I think that it can take one or two options - they can live in test/test_contrib or be right next to the actual files. I'd be fine with either and potentially both as long as we can pytest ignore what we want.

For what is in main vs contrib, I think that we can easily agree on the quality of tests, value and docs around each of them. For the substance of included in the main package, I think that it should be on a case by case basis. I agree that all first time contributors should plan to add to `contrib` and we can elevate it to the main package if it is makes sense. 

There might be certain things like the `StatsModelsWrapper` that likely should always live into contrib as it is outside of our support ecosystem of scikit-learn unless we explicitly want to change direction.

**Comment by bbengfort** [comment]
Also, Keras models would be very interesting to put into contrib.

**Comment by NealHumphrey** [comment]
One additional thought - what do you think about mirroring the project structure underneath the contrib folder? That way it will encourage people to put their new visualizers in the "right" place and thus make migration (slightly) easier, but still maintaining separation. 

Also, instead of `contrib` what do you think about a name that encourages the thought that these are bleeding-edge features that people are free to use but that they aren't yet ready for the maintenance track of normal visualizers - meaning even if they go out in a release, we make no guarantees of backwards compatibility if some initiual use shows that a different API format would be better (parameter names, etc). This would also reinforce the idea that any new visualizer should start its lifecycle here, get some stress testing by actual use to make sure it makes sense, and eventually move into the mainstream. 

Ideas:
`sandbox`
`dev`
`latest`
`alpha`
`beta`
`edge`

**Comment by bbengfort** [comment]
I think mirroring (as far as it will allow) is probably a good idea. 

The more I think about `contrib`, however, the more I think that it's going to be a place where visualizers that will never be included in the main yellowbrick package will go. For example, I've already talked to several people about:

- statsmodels visualizers 
- tensorflow and keras visualizers 
- classification selection visualizers using [ATM](https://github.com/HDI-Project/ATM) 

@NealHumphrey the names you suggested are more reminiscent of branches than alternative packages. Perhaps we should create an `edge` or `alpha` branch that parallels `develop`? 

@ndanielsen did you want to take the lead on `contrib` or how did you want to go about it?

**Comment by ndanielsen** [comment]
@NealHumphrey I agree with the mirroring idea. It's probably the most maintainable as well.

As for `contrib` naming convention, I appreciate the rationate behind your suggestions. I do agree with @bbengfort that it is a place for non-core visualizers and other utilities that are out of our core support of scikit-learn. I've been thinking that for the prototype / experimentation visualizers, we might want to include a warning with them making it clear that they are prototypes.

@bbengfort I'm okay taking the lead on `contrib` after I get the initial crop of missing values vizualizers out the door.

**Comment by ndanielsen** [comment]
@bbengfort 

Regarding tests for `contrib`, I don't think that we shouldn't pytest ignore the `test_contrib` module. As we'll be having quite a bit of related non-core utilities,  we need to test these. I recommend that we make generous use of `skipifs` and `expectedfailure` type utilities if we need to.
