### ISSUE TITLE
`statsmodels` test is skipped if `statsmodels` not installed (it isn't in the `requirements`)

### ISSUE THREAD

**Issue by ianozsvald** [DistrictDataLabs/yellowbrick#390]
In the recently added https://github.com/DistrictDataLabs/yellowbrick/pull/383 there's a bug - `statsmodels` is imported incorrectly (I have a PR fix, this was my bug as my original code didn't signal what to import). We nearly missed this as using a clean environment lacks `statsmodels` and consequently your tests skip `test_contrib/test_statsmodels $ pytest`.

### Proposal/Issue

We probably _don't_ want `statsmodels` to be a dependency of the main `yellowbrick` but maybe it should be a `testing/requirements.txt` dependency?

I note that you've marked this as being skippable https://github.com/DistrictDataLabs/yellowbrick/blob/develop/tests/test_contrib/test_statsmodels/test_base.py#L33 but I wonder if this just leads to trouble down the road if test behaviour is inconsistent between machines?

**Comment by bbengfort** [comment]
This is certainly a primary discussion point surrounding the `contrib` module, where we are also planning packages with dependencies on `nltk`, and `keras`. You're right that we don't necessarily want to add these dependencies to Yellowbrick core - but give the user information that the extra dependency is required, e.g. 

```python
try:
    import statsmodels.api as sm 
except ImportError:
    raise ImportError(
        "the yellowbrick.contrib.statsmodels package requires statsmodels, "
        "please install it with pip or conda"
     )
```

The issue is that when it comes to tests, we're also already balancing a pretty delicate depedency tower -- we're still struggling to ensure that our matrix of OS/Python Version/CI works in all cases, and I'm worried throwing in test dependencies wouldn't help with that. 

Right now I'm thinking we do the following:

1. add a tests/test_contrib/requirements.txt file 
2. add an environment variable `$TEST_CONTRIB` or something like that 
3. if the environment variable is set to true, then install these requirements and test contrib (or raise exceptions if things aren't installed) 

This might offer us the best flexibility, we can then set up one of the CI matrixes to test contrib, but make it not required for passing in order to merge?

@ndanielsen - any thoughts?

**Comment by bbengfort** [comment]
@ianozsvald just pushed some changes that might help

**Comment by bbengfort** [comment]
Closed for backlog grooming purposes.
