### ISSUE TITLE
Windows Image Similarity Tests

### ISSUE THREAD

**Issue by ndanielsen** [DistrictDataLabs/yellowbrick#423]
A good suggestion came out from @jkeung at pycon2018, we should investigate creating separate baseline images for windows machines.

Recommend that we had a check in the base.py for if the machine is windows and then direct the test to checkout the windows folder in baseline images or otherwise, significantly increase the tolerance for them.

**Comment by rebeccabilbro** [comment]
Here are the [actual images and diffs](https://drive.google.com/open?id=0B5pgYPYyUFpzS3FteGgzcjRRNlNSOWtkd1Njb3d1aGZJRy04) that result from running the tests on Windows with Python 3.6 and YB 0.8.

**Comment by bbengfort** [comment]
Following along on this -- 

@drwaterman and I went through all the windows image similarity errors and recorded the RMSEs and inspected them. The values can be found here:

[YB XFails List](https://docs.google.com/spreadsheets/d/1coQakoVoxqev2UVLpOolrd6uNhi9aFhm2PWkkgBCjZA/edit?usp=sharing)

We couldn't find any similarity errors that weren't related to text. @drwaterman notes in #567:

> @bbengfort If you are interested in reducing the RMSE for the Windows tests, I did a little playing around and I think if you turn off text antialiasing you can get rid of some of the text shadowing that we saw in the windows diff files. I added the following to a couple of the tests:
>
> At imports: import yellowbrick.style.rcmod as yb_rcmod
> At the beginning of a testing method: yb_rcmod.set_aesthetic(rc={'text.antialiased': False})
>
> Then comparing the output images from a windows machine and a mac machine, most of the text shadows disappear.
>
> There may be further rcmod parameters that can do similar things for the other rendered elements, I only tested with the text.
>
> The reduction in RMSE wasn't huge so you might not want to spend the time to implement this change unless a fix can also be found for the other elements.

**Comment by bbengfort** [comment]
I propose the following:

Phase 1: Increase tolerance if on Windows 
Phase 2: Implement backoff with tiered tolerances 

Backoff strategy:

1. before calling `assert_images_similar`, call `viz.finalize()` to ensure the entire viz is produced. 
2. have `assert_images_similar` accept a target threshold and a backoff threshold 
3. The backoff strategy will generate the image and test it, passing when the image comparision is <= the target threshold, and backing-off so long as the <= the backoff threshold; if > than backoff threshold or if all backoff images are exhausted, then the test fails. 
4. If we backoff, we can issue a test warning 

The backoff method requires us to keep multiple baseline images, but instead of for multiple operating systems, we're decreasing the number of visual elements. This will hopefully allow both windows and mac/linux users to generate baseline images but still be confident in the tests passing? 

Backoff steps:

1. Original image with all visual elements 
2. Remove legend, ticks, ax labels, title (what we currently do) 
3. Remove spines and any matplotlib.Text artists

**Comment by ndanielsen** [comment]
I'm actively working on this in this branch.

https://github.com/DistrictDataLabs/yellowbrick/tree/add-windows-tolerance

**Comment by ndanielsen** [comment]
Related to PR #823 and issues #744 #690

**Comment by rebeccabilbro** [comment]
@ndanielsen @nickpowersys &mdash; can we close this now? 😁

**Comment by rebeccabilbro** [comment]
Marking this complete with the addition of #864
