### ISSUE TITLE
Add option to show percentage or number in Class Prediction Error Plot y-axis

### ISSUE THREAD

**Issue by kumard78** [DistrictDataLabs/yellowbrick#472]
**Class Prediction Error Plot** shows number of predicted classes on y axis, this chart will not be very useful if we have miss classification means very less number of instances for one of the classes.

If y-axis shows % of predicted classes that may solve this issue.

**Comment by bbengfort** [comment]
@kumard78 this is a good suggestion, thank you -- we'd be happy for a PR if you have time to put something together. 

For the sake of discussion, we could include the percentage on the right access and the count on the left, e.g. something like:

![chart](https://user-images.githubusercontent.com/745966/41209071-e465c624-6cf6-11e8-8070-afc4d445df4e.png)

(ignore the two bars). 

Although to get this correct, the scale of the ylimits on both the right and left axis must be computed correctly. 

If this is too complex or not informative, a simple argument to the visualizer to display count or percentage would be fine, there are a number of visualizers that do this. 

@lwgray

**Comment by kumard78** [comment]
It will be great if 3 radio buttons can be added on top right corner for **counts, percentage and both** if no option is given to visualizer.
By default option **both** will be selected which will show the chart as shown above counts on left y-axis and percentage on right y-axis. it will create 2 bars, one for each y-axis.
As user clicks on radio button it will redraw chart.
If a option (counts/percentage) is to visualizer then corresponding chart should be shown with only one y-axis on left.

**Comment by rebeccabilbro** [comment]
Hi there @kumard78 -- iPywidget-style radio buttons certainly open up some neat options for interactivity for visualization! However, since we want Yellowbrick to work equally well with or without a Jupyter notebook, it's probably best to add the percentage options as an additional param on the `ClassPredictionError` class. 

Perhaps we can do something akin to what @NealHumphrey did for `ConfusionMatrix`, where there's a [`percent` param](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/classifier/confusion_matrix.py#L66) that determines whether to present the percent or raw count, or to @ariley1472's [recent update](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/classifier/classification_report.py#L67) to `ClassificationReport` that now allows for optionally showing the support as either percent or count. 

`ClassPredictionError` could have both, and maybe should default to count rather than percent, though I'm not very opinionated on this. This would make a great first Yellowbrick PR if you want to take a stab at prototyping it @kumard78!

**Comment by kumard78** [comment]
Thanks @rebeccabilbro and @bbengfort, i would love to prototype this feature/change.

**Comment by rebeccabilbro** [comment]
Awesome! Go ahead and open up a PR as soon as you like, and let us know if we can help!

**Comment by lwgray** [comment]
@kumard78 Again thanks for this suggestion.  I just wanted to check in with you to see if there is anything we can do to help you with setting up a PR for this issue.

**Comment by kumard78** [comment]
Sorry, I got busy in other stuff after the certificate program, I will
start working on it soon and will ask if i need help.

Thanks & Regards,
Deepak Kumar
Glen Allen, VA 23059
Cell : 571 439 6006
Work/Home: 804 527 2047

**Comment by lwgray** [comment]
@kumard78 No worries, I just wanted to make sure you know that we are here to help.

**Comment by rebeccabilbro** [comment]
Hi @kumard78 - going to close this one for now since the conversation has gone a bit stale; but feel free to reopen if you decide to pick this back up!
