### ISSUE TITLE
FeatureImportances not working with LogisticRegression

### ISSUE THREAD

**Issue by zfernandes93** [DistrictDataLabs/yellowbrick#485]
**Describe the bug**

FeatureImportances visualizer does not work with LogisticRegression. This is because instead of outputting coef_ as a list of numbers, LogisticRegression outputs the coef_ as a list within a list

**To Reproduce**

%%matplotlibmatplot  inline

import pandas as pd
import yellowbrick as yb
import matplotlib.pyplot as plt 

from sklearn.linear_model import LogisticRegression, Lasso
df = pd.read_csv('data/occupancy/occupancy.csv')

features = [
    "temperature", "relative humidity", "light", "C02", "humidity"
]
classes = ["unoccupied", "occupied"]

X = df[features]
y = df['occupancy']

** You'll see that like most classifiers, Lasso outputs coef_ as list
la = Lasso()
la.fit(X,y)
print(la.coef_)

** LogisticRegression outputs a list inside of a list
lr = LogisticRegression()
lr.fit(X,y)
print(lr.coef_)

** If you want to see the Error 
visualizer = FeatureImportances(LogisticRegression(), relative = False)
visualizer.fit(X, y)
visualizer.poof()

**Traceback**
IndexError: index 14 is out of bounds for axis 0 with size 1

**Desktop (please complete the following information):**
 - OS:  macOS
 - Python Version 3.6
 - Yellowbrick Version 0.7

**Comment by rebeccabilbro** [comment]
Good catch @zfernandes93! 

It looks like in this case scikit-learn's [`LogisticRegression`](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html) `coef_` returns a multidimensional array, in anticipation that there will be multiple classes and decision function coefficients for each class. In the case of a binary classification, the shape of `coef_` is (1, n_features), for multiclass it will be (n_classes, n_features), but either way `FeatureImportances` will break because it's expecting a flat array. 

We could go about addressing this in the [`FeatureImportances` visualizer](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/features/importances.py#L120) by checking the shape of `self.feature_importances_` somewhere in `fit` around [L124-147](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/features/importances.py#L124). If it's a multidimensional array we could stack the importances per class using something like [this](https://stackoverflow.com/questions/16653815/horizontal-stacked-bar-chart-in-matplotlib/16654564#16654564) in our [`draw` method](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/features/importances.py#L171). If we go this route, we may want to consider adding a target labels attribute to the class à la the [`ClassificationScoreVisualizer`](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/classifier/base.py#L67).  

Alternatively we could artificially flatten the array by simply averaging the per-class feature importances for each feature. 

Thoughts @bbengfort @ndanielsen @pdamodaran @lwgray?

**Comment by lwgray** [comment]
My first inclination is to flatten the array.

**Comment by rebeccabilbro** [comment]
Okie doke, working on this [now](https://github.com/DistrictDataLabs/yellowbrick/pull/490).
