### ISSUE TITLE
Model Selection Tutorial link to dataset is broken

### ISSUE THREAD

**Issue by joelvanveluwen** [DistrictDataLabs/yellowbrick#499]
@rebeccabilbro it looks like the link to agaricus-lepiota.txt is broken on http://www.scikit-yb.org/en/latest/tutorial.html which is pointing towards this link https://github.com/rebeccabilbro/rebeccabilbro.github.io/blob/master/data/agaricus-lepiota.txt

The data appears to be formatted/ labeled slightly different to its original form. If you've got the version you used the tutorial I'm happy to fix the link - if not I can just reformat the tutorial for the expanded set from UCI. Up to you!

Cheers,

**Comment by ndanielsen** [comment]
@joelvanveluwen thanks for raising this issue. I'll defer to @rebeccabilbro on this

**Comment by rebeccabilbro** [comment]
Thanks @ndanielsen and good catch @joelvanveluwen, thank you!! 

I've just implemented a temporary fix as a stop-gap -- but would you mind creating a new issue to update the tutorial to use the mushrooms data that comes with the new Yellowbrick [`datasets/download` module](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/datasets/download.py)(e.g. following the instructions [here](http://www.scikit-yb.org/en/latest/api/datasets.html))? We'd love to have you work on that @joelvanveluwen!

Note that we are *not* using the original version of the dataset that comes from the UCI repository; the reason is actually kind of funny -- some of our students pointed out that the original data is too good, and results in perfect classifiers, which don't really illustrate the value that YB classification score visualizers have for real world, messy data. Our version has some details removed to keep things interesting ;)

**Comment by joelvanveluwen** [comment]
@rebeccabilbro happy to help out - I will create an issue! I don't encourage people to use UCI for some of the team I train for this very reason! Glad to know you have put the effort in to make an environment that somewhat resembles reality.
