### ISSUE TITLE
Isolate Yellowbrick Dependencies

### ISSUE THREAD

**Issue by mariusvniekerk** [DistrictDataLabs/yellowbrick#52]
Lots of libraries are pinned to versions in the requirements.txt

Should this be the case?

**Comment by bbengfort** [comment]
@mariusvniekerk the current version is an mvp proof of concept, intended for development and not necessarily users. We've been having a lot of trouble with continuous integration testing (see #17 #20) and so we felt that pinning versions would be necessary to ensure we were all on the same page. 

That said, most of the libraries in requirements.txt are commented out, and only the following dependencies are pinned:

```
matplotlib==1.5.1
scipy==0.17.1
scikit-learn==0.17.1
numpy==1.11.0
cycler==0.10.0
```

The others are mostly dependencies of these 5 and come into the requirements with `pip freeze`. 

You do, however, raise a good point - and we've recently been discussing what dependencies we want to include, and whether or not we want to include Seaborn and the entire pandas stack, or try to simplify the library. We have decided the following dependencies are going to be in Version 1:

```
matplotlib>=1.5.1 
scikit-learn>=0.17
``` 

I'm going to go ahead and make this issue reflect that goal so that we can discuss its impact here!

**Comment by mariusvniekerk** [comment]
Thanks,  basically I wanted to build a conda package for yellowbrick.

For CI purposes I would strongly advocate using conda and conda-forge to grab your dependencies.  You can get latest versions of the various pydata stack libraries and it should be relatively easy to test against multiple different versions of scipy, sklearn and matplotlib.

**Comment by bbengfort** [comment]
Excellent! We'd really appreciate a conda package contribution. Just note that we're about to make some significant changes to the underlying API, refactoring to our idea of "Visual Transformers" and "Visual Pipelines" to more closely align ourselves with the Scikit-Learn Pipeline. These changes are due October 6 in the 0.3 release of Yellowbrick, which will not be backwards compatible.

**Comment by bbengfort** [comment]
Version 0.3.1 froze the dependencies as follows:

```
matplotlib>=1.5.1
scipy>=0.17.1
scikit-learn>=0.17.1
numpy>=1.11.0
cycler>=0.10.0
```

**Comment by bbengfort** [comment]
@mariusvniekerk -- I'll create a new issue for the conda package distribution.
