### ISSUE TITLE
ConnectionError: HTTPSConnectionPool.who can give me a piece of data?

### ISSUE THREAD

**Issue by YSZYCF** [DistrictDataLabs/yellowbrick#550]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mowar\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Mowar\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Mowar\Anaconda3\lib\site-packages\yellowbrick\download.py", line 148, in <module>
    download_all(path)
  File "C:\Users\Mowar\Anaconda3\lib\site-packages\yellowbrick\download.py", line 143, in download_all
    download_data(url, path=path, signature=signature, extract=extract)
  File "C:\Users\Mowar\Anaconda3\lib\site-packages\yellowbrick\download.py", line 114, in download_data
    response = requests.get(url, stream=True)
  File "C:\Users\Mowar\Anaconda3\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Mowar\Anaconda3\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Mowar\Anaconda3\lib\site-packages\requests\sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Mowar\Anaconda3\lib\site-packages\requests\sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Mowar\Anaconda3\lib\site-packages\requests\adapters.py", line 502, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /ddl-data-lake/yellowbrick/concrete.
zip (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000078C6CC0>: Failed to establish a new connec
tion: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))

I have  followed the instructions from downloading example datasets. but I alway get ConnectionError. maybe I come from china. who can give me a piece of data?

**Comment by lwgray** [comment]
@YSZYCF I am sorry you are running into this problem.  The first step for us is to replicate the error.  Can you provide the following?

1.  The code you used that generated the error
2.  The version of yellowbrick you are using
3.  The version of python you are using
4.  A list of packages in your conda or pip environment

**Comment by bbengfort** [comment]
@YSZYCF Yes, it's certainly possible that the exception you're getting is due to your proxy settings or a firewall. Out of curiosity can you load the [`sklearn.datasets`](http://scikit-learn.org/stable/datasets/index.html)? If so, the `load_boston` dataset is similar to the concrete dataset. 

Alternatively you can find all of our datasets at the [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/), including the [concrete dataset](http://archive.ics.uci.edu/ml/datasets/concrete+compressive+strength), though note that we've done some wrangling on the original data to make it easier to load into our tutorials. 

@lwgray one way we could provide the datasets is that we could create a GitHub repository with the zip files in them, @YSZYCF clearly has access to GitHub, right?

**Comment by YSZYCF** [comment]
@lwgray I use this command to download dataset. python -m yellowbrick.download.
Name: yellowbrick
Version: 0.8
Summary: A suite of visual analysis and diagnostic tools for machine learning.
Home-page: https://github.com/districtdatalabs/yellowbrick
Author: Rebecca Bilbro, Benjamin Bengfort
Author-email: info@districtdatalabs.com
License: Apache 2
Location: c:\users\mowar\anaconda3\lib\site-packages
Requires: scipy, matplotlib, cycler, numpy, scikit-learn

**Comment by Kautumn06** [comment]
@YSZYCF I'm sorry you're having a problem downloading the datasets. Fortunately, as @bbengfort mentioned, the `concrete` dataset is on the [UCI Machine Learning Repository](http://archive.ics.uci.edu/ml/datasets/concrete+compressive+strength). And while we do wrangle some of our sample datasets to make them easier to use in our examples, their `concrete` dataset is virtually identical to ours. They both have 1030 instances and 9 attributes and neither is missing any data, so you should receive very similar results to those you find in our documentation.

**Comment by Kautumn06** [comment]
Also @YSZYCF, since you can access GitHub, you might find it helpful to use [Seaborn's sample datasets](https://github.com/mwaskom/seaborn-data). Similar to ours, they have already been wrangled to make them easier to use. And they have datasets such as `iris` and `titanic`, which are used quite frequently in machine learning tutorials.

**Comment by YSZYCF** [comment]
@Kautumn06 Thank you for your help.

**Comment by lwgray** [comment]
@YSZYCF if you would like to download the exact datasets used by Yellowbrick then you can access them [here](https://github.com/lwgray/ybdatasets)

**Comment by Kautumn06** [comment]
Thank you for your interest @YSZYCF and I hope you keep using Yellowbrick!
