### ISSUE TITLE
Verify and document quick methods

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#600]
Our codebase is primarily class-based, however we do have quick-methods for quickly drawing a visualizer from data without a lot of setup (for the common case). Unfortunately, most of these quick methods are undocumented and are not verified. Before the 1.0 release, it would be good if we could include them in our documentation. 

Verifications:

- Does the quick method return a visualizer? (Most probably return an axes object) 
- Does the quick method have an associated test? 
- Does the quick method support all its parent visualizer arguments? 
- Does the quick method behave as expected?

For documentation:

- Should we create a new page for the quick methods? 
- Should we add the docstring automodule to the relevant documentation pages? 

Other questions:

- Should quick methods call `poof()` or `finalize()` should this be an argument (e.g. `poof=True`)? 
- Should quick methods do train/test splits? (See ROCAUC and PrecisionRecallCurve) 
- Do the quick methods require other arguments? 
- Is there any reason not to make the quick methods prime time?

**Comment by bbengfort** [comment]
Marked as high priority for the version 1.0 release (not v0.9)

**Comment by Kautumn06** [comment]
@bbengfort I've finished documenting all of our quick methods in the Yellowbrick audit spreadsheet (#669). The information answers the first three questions under "Verifications" and the second question under "Other Questions" listed above.

**Comment by bbengfort** [comment]
@Kautumn06 awesome! Thank you so much! I'll take a look and then add some comments on this issue about what the next steps are to make this prime time. @ndanielsen would you mind also taking a look?

**Comment by Kautumn06** [comment]
@bbengfort Also, I did add two additional columns to the "Quick Methods" tab to record some additional information I noticed while finishing it. One column to track when a quick method has additional parameters not found in the Visualizer and another that contains notes about when a parameter has different defaults (for instance, `balanced_binning_reference` has `target='Frequency'` while `BalancedBinningReference` has `target=None`). 

The third column I added includes information about when I saw that the difference in parameter names was because of capitalization. For example, `freqdist` has the parameter `N=50`, while it is `n=50` in `FrequencyVisualizer` . Most of the additional examples where this occurred involved one having `x` while the other has `X`.

So I hope that this is helpful! Please just let me know if you have any questions.

**Comment by bbengfort** [comment]
@Kautumn06 very helpful! Now that we have the audit I think we need to do the following:

- [ ] repair all return values 
- [ ] ensure all quick methods have tests 
- [ ] ensure none of the parameters are missing 
- [ ] figure out a documentation mechanism for the quick methods 
- [ ] document the quick methods 

So the question is how do we move forward? #687 is an exhaustive list of what needs to be done with plot directives, do we do something like that here? Do we create new issues for these tasks?

**Comment by bbengfort** [comment]
An example of a quick method and a visualizer with detailed doc strings that discuss how best to create meaningful interactions between the two: (I tried to come up with the trickiest quick method that needs to be implemented for discussion)

https://gist.github.com/bbengfort/5d5b211c1cf49f7dac147654e75e5d24

**Comment by ndanielsen** [comment]
@bbengfort thanks for posting that gist. Super helpful documentation of the visualizer and quick method patterns

**Comment by rebeccabilbro** [comment]
As part of the visualizer audit #669 (in #945, #940, #938, #936), we have been updating all the quick methods to [return the visualizer](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/classifier/class_prediction_error.py#L261) rather than the axes (which is consistent with our [current guidance to contributors](http://www.scikit-yb.org/en/develop/contributing/advanced_development_topics.html#code-conventions)). However, Matplotlib issues warnings (related to the `agg` backend) when we call `poof` inside the quick method instead of `finalize` &mdash; so it would be worth it to take another pass through all the quick methods and update the ones that currently call `poof` to instead call `finalize`.

**Comment by rebeccabilbro** [comment]
Let's also verify that each quick method has an associated test!

**Comment by bbengfort** [comment]
Closed in favor of #960 and the visualizer audit that was just conducted.
