### ISSUE TITLE
Support Vector Machines and ROCAUC

### ISSUE THREAD

**Issue by FranGoitia** [DistrictDataLabs/yellowbrick#606]
**Describe the bug**
ROCAUC fails with support vector machines. This doesn't happen to me with other algorithms.

**To Reproduce**

```python
model = SVC()
viz = ROCAUC(model, n_jobs=-1)
viz.fit(X_train, y_train)
viz.score(X_test, y_test)
```

**Dataset**
I'm using the credit dataset on Yellowbrick

**Expected behavior**
To obtain the ROC plot

```
/media/Data/Gatech/machine-learning/supervised-learning/helpers.py in plt_roc(model, X_train, y_train, X_test, y_test)
     30     viz = ROCAUC(model, n_jobs=-1)
     31     viz.fit(X_train, y_train)
---> 32     viz.score(X_test, y_test)
     33     return viz
     34 

~/venvs/global/lib/python3.6/site-packages/yellowbrick/classifier/rocauc.py in score(self, X, y, **kwargs)
    176         # Compute ROC curve and ROC area for each class
    177         for i, c in enumerate(classes):
--> 178             self.fpr[i], self.tpr[i], _ = roc_curve(y, y_pred[:,i], pos_label=c)
    179             self.roc_auc[i] = auc(self.fpr[i], self.tpr[i])
```

`IndexError: too many indices for array`

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python Version: 3.6.5
 - Yellowbrick Version: 0.8

**Comment by bbengfort** [comment]
@FranGoitia the ROCAUC visualizer has had some improvements that may fix this problem with the 0.9 release, we can check to see if this behavior has been resolved. What was the exception you were getting?

**Comment by bbengfort** [comment]
@DistrictDataLabs/team-oz anyone interested in taking a look to see if the new version of ROCAUC solves this issue?

**Comment by rebeccabilbro** [comment]
Hi @FranGoitia and thanks for reporting this bug! 

Fortunately, after some research ([see notebook here](https://github.com/rebeccabilbro/yellowbrick/blob/rocauc-svm-check/examples/rebeccabilbro/rocauc_svm_check.ipynb)), it looks like this has been successfully addressed by #533 and #540. 

For background, the bug was triggered whenever a user employed `ROCAUC` for binary classification with a scikit-learn estimator that has only a decision_function (like SVM). This is because the default params for YB's `ROCAUC` are `micro=True`, `macro=True`, and `per_class=True`, however, when an estimator with only a decision function is used for binary classification, there will only be enough information to plot a single curve! 

The version of `ROCAUC` currently in the develop branch (though not yet in master) attempts to detect binary decision functions and handle them accordingly. 

*Note: This solution requires the user to set `micro=False`, `macro=False`, `per_class=False` when using a binary decision function estimator. If you forget, you get a nice descriptive error message*

```
viz = ROCAUC(SVC())
viz.fit(X_train, y_train)
viz.score(X_test, y_test)
viz.poof()
```
results in:
```
ModelError: Micro, macro, and per-class scores are not defined for binary classification for estimators with only decision_function methods; set micro, macro, and per-class params to False.
```

While:
```
viz = ROCAUC(SVC(), micro=False, macro=False, per_class=False)
viz.fit(X_train, y_train)
viz.score(X_test, y_test)
viz.poof()
```
makes:
![image](https://user-images.githubusercontent.com/8760385/45588163-1935b200-b8de-11e8-8f9b-6320a75286e4.png)

Hope this helps and thanks again for letting us know about this! If you notice other bugs, please don't hesitate to open a new bug report!!

**Comment by FranGoitia** [comment]
Thank you for fixing it and working on such a fantastic library !
Best,
Fran

**Comment by TaiChiTiger** [comment]
if you set ```probability=True```, it will work

**Comment by TaiChiTiger** [comment]
if you set ```SVC(probability=True)```, it will work

**Comment by bbengfort** [comment]
Thanks @TaiChiTiger for your note!
