### ISSUE TITLE
Custom Color Palette

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#64]
Yellowbrick needs a coordinated color palette that is some version of blue/green/red/maroon/yellow/cyan/black

**Comment by rebeccabilbro** [comment]
Those color descriptions can be pretty flexible. The main thing is that each is a single letter color code, which is convenient for users.

The current versions are [here](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/examples/palettes.ipynb). The one we are using is the one called Yellowbrick.

**Comment by rebeccabilbro** [comment]
@justjess - any interest in checking out this issue? We'd love to list you as an official Yellowbrick contributor. It's an open source project that @bbengfort and I have been working on that's based on the work I presented at PyCon that you helped me with. You can read more about it [here](https://github.com/DistrictDataLabs/yellowbrick/blob/master/README.md), and I'd be happy to answer any questions you have!

**Comment by justjess** [comment]
You bet! Let me take a look.

**Comment by stvn66** [comment]
Looking at your [palettes notebook](https://github.com/DistrictDataLabs/yellowbrick/blob/master/examples/palettes.ipynb), you have a lot of great options.  It is nice that you have the seaborn palettes, and it looks like some of the qualitative [brewer ones]() as well.

I was recently looking at the palettes from [matplotlib 2.0](http://matplotlib.org/devdocs/users/dflt_style_changes.html#colors-color-cycles-and-color-maps), which is using [vega category10](https://github.com/vega/vega/wiki/Scales#scale-range-literals) as their new default.  While another nice option, I thought you may want to look at how they are cycling through the new default.  Their new setup provides a 2 letter string representations which does not require the one letter abbreviations.  This is nice as several nice palettes cannot be easily represented with the one letter strings.  

Regardless of which palette you decide on, I thought this might be something you would like to consider.  This is especially nice for iterating through a palette that has two colors with the same first letters.  Using labels independent of the color name allows you to iterate through any chosen palette, regardless of the names (for example, users could select the dark palette then iterate using 'C0', 'C1', 'C2', etc).

**Comment by bbengfort** [comment]
@stvn66 thanks for your comment! Our goal with the palettes are to give as many choices as possible because what we've observed in high dimensional analysis, particularly related to feature analysis, is that color has an important role in being able to detect or understand separability. And folks perceive and interpret colors differently. That's why we brought over the seaborn `set_palette` function, which also modifies the `bgrmyck` single character color codes. 

ColorBrewer and the vega readability scale are important from a visualization perspective as they take into account color blindness and general color interpretation therefore we must include them! We hope to bring in as many palettes as possible including the rest of the brewer sequential, diverging, and categorical palettes #57. 

The point of this issue was to get a yellowbrick-identity palette just so we had a yellowbrick look and feel similar to Seaborn - we want all Visualizers to fit together meaningfully by default so that we don't disrupt analysis. We also want to take into account the [viscm](https://bids.github.io/colormap/) work by Van der Walt also included in Matplotlib. 

In terms of the 2 character color codes - we are also very excited about that especially after seeing [Thomas Caswell's talk at PyData Carolinas](https://www.youtube.com/watch?v=wwUIEflrTCk). I actually just said in a development discussion that we should "wait and see what Seaborn does with the 2 character color codes". However, if you have any ideas for how we could implement this, we'd love to hear them in a new issue. 

Check out [set_color_codes](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/style/palettes.py#L288) to see how we're doing this with the single character codes right now.

**Comment by stvn66** [comment]
Here is another color palette to consider ([source](http://jfly.iam.u-tokyo.ac.jp/color/)) from [ggplot2](http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/).
![pallete](https://cloud.githubusercontent.com/assets/9484229/19423744/6cc3b6f6-93f1-11e6-848f-0e259465abef.jpg)

**Comment by bbengfort** [comment]
@stvn66 absolutely, I think our approach with palettes should be the more the merrier, especially named palettes! 

We already have a `colorblind` and `sns_colorblind` palette in [palettes.py](https://github.com/DistrictDataLabs/yellowbrick/blob/master/yellowbrick/style/palettes.py#L75) but I have no idea where we got the `colorblind` palette. Would you be interested in contributing this as a pull request? It would get you the contributor attribution! 

I would go about this as follows: 

- [ ] rename the current `colorblind` palette `cb_original` 
- [ ] alias the `sns_colorblind` palette to `cb_seaborn` (e.g. copy that line and change the name) 
- [ ] create a `colorblind` palette that matches the above colorspace; note that it would be good if we maintained the matplotlib ordering of `['blue', 'green', 'red', 'maroon', 'yellow', 'cyan']`, which looks like it would be `Blue, bluish Green, Vermilion, reddish Purple, Yellow, Sky Blue, Orange` in this case. 
- [ ] create an alias for `colorblind` called `cb_ggplot2` 
- [ ] update the [palettes notebook](https://github.com/DistrictDataLabs/yellowbrick/blob/master/examples/palettes.ipynb) so that we can see the new colors (basically just run all and save). 

In the pull request if you could cite the source from above too, that would be great! 

Let me know if you're interested (should be pretty easy); otherwise I can toss it in there if you'd prefer.

**Comment by rebeccabilbro** [comment]
Hey there @justjess - still up for making a custom yellowbrick palette? Now that you're on the Team Oz Collaborators, we can assign the card to you to formally credit you with taking this one on. It's read-access, so you'll still need to do a pull request.  We'd love to have you contribute a special coordinated color palette. As long as it's in the blue/green/red/maroon/yellow/cyan/black family, you have complete creative control!

**Comment by bbengfort** [comment]
Backlog grooming
