### ISSUE TITLE
Add a UMAPVisualizer for text data

### ISSUE THREAD

**Issue by jc-healy** [DistrictDataLabs/yellowbrick#666]
After seeing Rebecca speak at PyDataNY I promised her a text/UMAPVisualizer as a drop in replacement for the current text/TSNEVisualizer currently in Yellowbrick.

**Comment by jc-healy** [comment]
I had a look at your 'how to contribute page' so I'm creating a waffle ticket.  Not sure how to assign it to myself though.  The UMAPVisualizer was pretty straight forward so I was able to finish it up quite quickly.  You're how to contribute to Yellowbrick page was quite excellent and made the process of integrating code into your project quite smooth.  Thank you for that.  I'll put in a pull request and we can go from there.

**Comment by wagner2010** [comment]
Thank you so much @jc-healy for complimenting us on on our 'how to contribute page'.  We strive to make contributing to yellowbrick easy because we rely heavily on our contributors to strive for improvements.  Thank you even more for submitting your PR and following up with @rebeccabilbro .  We can't wait to review it!  Stay well and let's stay engaged.

**Comment by bbengfort** [comment]
Se #667

**Comment by bbengfort** [comment]
Closed in #667
