### ISSUE TITLE
Unclear target of readme, some feedback on install docs

### ISSUE THREAD

**Issue by amueller** [DistrictDataLabs/yellowbrick#689]
The readme says "This README is a guide for developers, if you're new to Yellowbrick, get started at our documentation.", but I'm not sure if the content is appropriate in this case.
It provides instructions for installing from pip, but not from a build folder (is ``pip install -e . `` recommended?) and no instructions for running tests.

There's pretty extensive instructions at http://www.scikit-yb.org/en/latest/contributing.html , maybe I'd make them more prominent.

It's not clear to me why you recommend using the requirement.txt directly instead of  ``pip install -e .`` - if you install the requirements via the requirements.txt, you're not adding the directory to your ``PYTHONPATH`` so you can't run tests, right?

**Comment by ndanielsen** [comment]
@amueller thanks for stopping by and for this feedback. I'll take a look and address shortly!

**Comment by ndanielsen** [comment]
> The readme says "This README is a guide for developers, if you're new to Yellowbrick, get started at our documentation.", but I'm not sure if the content is appropriate in this case. ... and no instructions for running tests.

Thank you for this helpful feedback. I agree that the `readme` seems to be sending mixed messages. I'll discuss with the maintainers group about this as we have had several discussions about revamping/ streamlining our documentation as part of our upcoming 1.0 release. 

> It's not clear to me why you recommend using the requirement.txt ...

As for the running tests and installing dependencies, we run tests from the root of the folder as documented in code in the [`.travis.yml`](https://github.com/DistrictDataLabs/yellowbrick/blob/93d64c7bd90f194a6a2d8813407af42d482ad57c/.travis.yml#L10-L16
) file. 

My workflow is normally after cloning the project and moving into the yb dir is: 
- `pip install -r tests/requirements.txt`
- `make test`

We have a tests requirements file as we try to keep our dependencies small and limited but want to test support for libraries like pandas and nltk. I think that the test dependency installation might also help to address [this testing related issue](https://github.com/DistrictDataLabs/yellowbrick/issues/690) that you also opened. 

As for `It's not clear to me why you recommend using the requirement.txt directly instead of pip install -e . `, I think that with the testing workflow that we currently have is simple enough and just works. I do agree that we can point to and give more concise instructions to help new folks to the project to exercise our test suite!

**Comment by ndanielsen** [comment]
Partially addressing this issue here:
https://github.com/DistrictDataLabs/yellowbrick/pull/692

**Comment by amueller** [comment]
You run ``make test`` without adding anything to the path? I guess that works from that particular directory. But then you can't use the library because it's not installed, right?

**Comment by bbengfort** [comment]
@amueller - mind checking out the README again? @rebeccabilbro did some work streamlining it so that it does a better job of pointing to the docs. I think our goal from here on out is to primarily use the docs rather than in-code READMEs.

**Comment by bbengfort** [comment]
@amueller I believe your comments have been addressed in #731 and in #720 so I'm going to go ahead and close this issue. Let us know if you have any other feedback on our documentation, we're always looking to improve it!
