### ISSUE TITLE
Some YB tests fail with conda Python 3.7 & Matplotlib 3.x

### ISSUE THREAD

**Issue by amueller** [DistrictDataLabs/yellowbrick#690]
I'm trying to run the tests.
I get 133 failures, many of them
```
E   AssertionError: 'Qt5Agg' != 'agg'
```

Does running the tests require setting a specific backend?

**Comment by ndanielsen** [comment]
@amueller great question and apologies that the tests didn't pass on the first shot. 

The yb uses the [`agg` backend ](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/tests/base.py#L72)

Sometimes it needs to be set in the specific matplotlib config usually located at  `/.matplotlib/matplotlibrc`

Let me know if this helps with getting the tests passing!

**Comment by amueller** [comment]
I actually run "make test" which I thought was the sure-fire way to do it right ;)
Usually I would use pytest. The Makefile actually uses ``python setup.py test``.

Re config: according to ``matplotlib.get_configdir()``  it's in ``.config/matplotlib`` and it's empty.

Running ``pytest tests`` in the root YB directory yields the same errors.

**Comment by amueller** [comment]
I'm not on the same machine right now, but have the same problem on a different machine.
Also has an empty matplotlibrc, is using ubuntu 18.04.1, conda with python 3.7.1, matplotlib 3.0.2

**Comment by rebeccabilbro** [comment]
Ah, thank you very much for the additional details @amueller! I think I've figured out what the issue is.

Apparently, this is [a unique Anaconda bug](https://github.com/ContinuumIO/anaconda-issues/issues/10219#issuecomment-433712810) that occurs when using conda Python 3.7 and Matplotlib 3.x ([which updated the way that backends are set](https://matplotlib.org/users/whats_new.html#improved-default-backend-selection)). 

Fortunately, this bug should only affect YB tests for you, and for contributing (which I hope you're interested in!) if you don't mind using vanilla Python 3.x, you'll be able to avoid them entirely.  Alternatively, you can manually set the backend using the workaround described by @nehaljwani. 

In the meantime, I've reported the behavior you observed on that Anaconda issue, which we'll track closely. Our tests are currently passing on Travis with pure Python, and on AppVeyor with Windows and miniconda. As soon as the Anaconda issue is resolved, we can add miniconda to our Travis test matrix, too (assuming it’s available) so that we can keep an eye on it moving forward!

**Comment by amueller** [comment]
Hm I wouldn't consider that an anaconda bug but a matplotlib feature? I pinged Thomas but I'm not sure if he has time for this kind of detail stuff.
The issue you linked to seems somewhat different because it calls ``get_backend`` first. As long as you call ``use`` first it should work, right? An alternative work-around would be ``force=True``.

I think a lot of people in the data science space use conda so it would be cool to have a work-around.

**Comment by tacaswell** [comment]
A sure-fire way to fix this is to set the `MPLBACKEND=agg` env which overrides any other configuration files.

**Comment by nickpowersys** [comment]
With matplotlib 3.0.3 on Windows, the backend tests pass for me when specifying backend as 'agg'. See PR #823. A small number of image comparison tests need to be resolved.

With matplotlib 3.0.3 on Ubuntu 16.04, even if no changes are made to the backend, the backend tests pass. A larger set of image comparison tests fail with conda packages installed on Ubuntu than on Windows, but all tests pass for me with PyPI / pip packages installed into a Miniconda environment.

**Comment by tacaswell** [comment]
I suspect that the issue is the version of freetype (which renders the text) varying between platforms / installations.

**Comment by bbengfort** [comment]
@tacaswell thank you for the note, it looks like [your solution](https://matplotlib.org/devel/contributing.html#building-matplotlib-for-image-comparison-tests) to this was to build a special version of matplotlib with a local freetype. Any chance there is a reference build to that hosted on a package index that we could use as a dependency for testing only?

**Comment by tacaswell** [comment]
There are packages on conda-forge for this purpose.

We obviously build Matplotlib from source as part of our tests so this is not something we have worried about.

@dopplershift and @qulogic may have more useful comments here.

**Comment by dopplershift** [comment]
You can install the testing version from conda-forge with `conda install -c conda-forge/label/testing matplotlib`. Looks like the latest we have there right now, though, is 3.0.2

**Comment by bbengfort** [comment]
@dopplershift and @tacaswell awesome, thank you -- we'll give that a try!
