### ISSUE TITLE
Matplotlib version (>=3.0.0) backends don't support Yellowbrick

### ISSUE THREAD

**Issue by Naba7** [DistrictDataLabs/yellowbrick#701]
**Describe the issue**
A clear and concise description of what the issue is.

@DistrictDataLabs/team-oz-maintainers
The error says YellowBrick  0.9 has requirement matplotlib <3.0 and >=1.5.1.So,the version of matplotlib without updating works fine.I will recommend users not to update matplotlib as its version 3.0.2's backends don't support yellowbrick.

**Comment by bbengfort** [comment]
@Naba7 Thank you for your note - as it turns out the issue was only with matplotlib 3.0.0 and the problem has been solved in 3.0.1, which Yellowbrick is compatible with. The new requirements file requires `matplotlib>=1.5.1,!=3.0.0`, which means any version of matplotlib > 3.0.0 is fine. 

If you're having a problem with `pip` install of Yellowbrick v0.9 let me know and we can get a hotfix for Yellowbrick v0.9.1 pushed to PyPI.

**Comment by ianozsvald** [comment]
Hey @bbengfort . I totally missed the release of Matplotlib 3.0.x. My client this morning just told me they'd dropped YellowBrick because it wouldn't install cleanly with mpl 3, I suggested they try a `pip install git+...` and they're giving it a go. Given that mpl 3 came out in September might it be possible that you're losing users elsewhere due to the perceived incompatibility? Personally I'd +1 the idea of a hotfix for mpl 3.0.2 support.
With that in mind - is there a need to do e.g. a round of testing on various mpl3.0.x systems that'd assist in derisking a new release?
