### ISSUE TITLE
Classifier and regression score visualizers no longer show

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#75]
Looks like in our last refactor, we changed something in our classifier and regression score visualizers, which means they no longer `show( )` (i.e. `poof` doesn't do anything anymore).

**Comment by rebeccabilbro** [comment]
@bbengfort this maybe something we didn't catch before because we were working in Jupyter. I ran into it in the command line:

```python
>>> visualizer.score(X,y)
<matplotlib.axes._subplots.AxesSubplot object at 0x10dda4898>
>>> visualizer.poof()
<matplotlib.axes._subplots.AxesSubplot object at 0x10dda4898>
```

I'll investigate and see if I can fix.

**Comment by rebeccabilbro** [comment]
@bbengfort ok, I've figured out what the problem was (we somehow dropped `show` from `poof` and were just returning the axes instead) and I've repaired the code  - should I push the bug fix to develop? or create a new branch? None of the score visualizers will work until the edits get merged in.

**Comment by bbengfort** [comment]
@rebeccabilbro good catch - go ahead and push to develop; oddly they did work in the notebook - but I suppose that's because the notebook displays the axes returned. Because of that and because the user can call `plt.show()`, I wouldn't call the bug severe. 

Though ... this actually does bring up another point. I was thinking that we might need a method like `finalize` or `done` to do work in advance of `show` or `savefig` (set titles, legends, limits, etc.) particularly for plots where draw may be called multiple times. Perhaps we should make `poof` this method and let the user call `show` or `savefig`? Or perhaps we should have a `show=True` kwarg in the `poof` function definition? 

Check out: [pcoords.py#L270](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/features/pcoords.py#L270) for my conditional show/savefig logic that I was using.

**Comment by rebeccabilbro** [comment]
@bbengfort ok, pushed the edits to develop to resolve this issue.  

I like the idea of some sort of finalization method, and have been thinking of yellowbrick as something that people might use as part of their research work for publication purposes; saving figures is an important component of that. I really like your pcoords example. I think `show=True` should be the default (or maybe `save=False`?), and users should be able to modify with a keyword. Shall we create a new issue for refactoring all the `poof` methods to allow for both show and save?

**Comment by bbengfort** [comment]
@rebeccabilbro yes, absolutely (to the new issue and going this route)! We should also ensure that `poof` returns the axes so that the notebook works by default. 

While we're at it, I just remembered why I didn't want `poof` to show (or to have the option not to show) and was thinking about some sort of finalize method. I wanted to create one-off helper functions so that people could get simple visualizations without all the work of instantiating the visualizer (sort of like the [`scale` function](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.scale.html#sklearn.preprocessing.scale) in Scikit-Learn): [pcoords.py#L35](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/features/pcoords.py#L35). 

These functions would simply instantiate the Visualizer, call `fit_transform` (which in turn calls `draw`) and would also have to call `poof` to finalize the figure. However, I was thinking these would work similarly to Seaborn's functions - which simply return an axes but do not call show on the behalf of the user. So the function could do `poof(show=False)` to get the legend, title, limits, etc. and return the axes. 

These functions are very similar to each other: [radviz.py#L34](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/features/radviz.py#L34); in fact only the docstring and the class used in the function body are different! We could probably create a factory function that generates these helper methods from visualizers. Would you mind making an issue for this feature as well?

**Comment by rebeccabilbro** [comment]
OK @bbengfort I've created a new issue for a finalization method (# 76).

Could you give me a better sense of what you have in mind for the helper functions you're describing? Is the idea to wrap the `__init__`/`predict-score`/`fit-transform`/`poof` sequence so that users can accomplish everything in a single call? Or is the idea to create a visualization object such that if the user calls `poof(show=False)` it can be saved and exported to a different tool, the way that you can export a NetworkX graph as graphml or gexf?

**Comment by bbengfort** [comment]
@rebeccabilbro yep the idea is to wrap the sequence so that users can accomplish a single visualization in a single call (e.g. for a one off visualization).  I'm still undecided if this should return the visualizer object or it should return the matplotlib axes. Some examples below:

```python
class MyFeatureVisualizer(FeatureVisualizer):
    ... 

def myfv(X, y=None, **kwargs):
    visualizer = MyFeatureVisualizer(**kwargs)
    visualizer.fit_transform(X, y=None) 
    visualizer.finalize() 
    return visualizer.ax
```

Here, because of #76 we don't have to worry about `poof` and can directly call finalize. Alternatively we can keep `poof` the finalize method and call `poof(show=False)` on the visualizer. 

Another example:

```python
class MyScoreVisualizer(ScoreVisualizer):
    ... 

def mysv(estimator, X, y, **kwargs):
    visualizer = MyScoreVisualizer(estimator, **kwargs)

    # Create the train/test split for evaluation 
    Xr, yr, Xt, yt = train_test_split(X, y) 
    
    # Fit and score the visualizer 
    visualizer.fit(Xr, yr)
    visualizer.score(Xt, yt) 

    visualizer.finalize() 
    return visualizer.ax 
```

These methods are quick one-off visualizations for users (and like I said, Scikit-Learn has stuff like this) -- though we'd prefer that they use the class interface directly, particularly with Pipelines. We can do stuff like choose the best visualizer for use in the function (e.g. parallel coordinates with feature order optimization) similar to how NLTK chooses the best tokenizer in `nltk.word_tokenize` but still exposes every class behind the scenes. 

They also pull a secondary duty by documenting how exactly we believe the visualizers should be interacted with. For example some `ScoreVisualizer` objects require train/test splits and cross validation, while others do not.
