### ISSUE TITLE
Add finalize method

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#76]
Add a `finalize` or `done` method to do work in advance of `show` or `savefig` (to set titles, legends, limits, etc.) particularly for plots where draw may be called multiple times.

**Comment by rebeccabilbro** [comment]
Essentially we want to add conditional show/savefig logic similar to what's in the [parallel coordinates `poof` method](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/features/pcoords.py#L255).
 
We should make  `save=False`  or `show=True` the default and allow users to modify with a keyword.  We also need to ensure that `poof` returns the axes in addition to calling `show` so that a Jupyter notebook works by default.

**Comment by rebeccabilbro** [comment]
`finalize` takes only self and generic keyword arguments.  The user calls `poof` and `poof` calls `finalize`.  `finalize` will do the subclass-specific axes finalization stuff, while `poof` does the generic show that all the subclasses will do. some subclasses may not have any `finalize`  things to do.

**Comment by rebeccabilbro** [comment]
@bbengfort can you do a quick review of commit [3550f67](https://github.com/DistrictDataLabs/yellowbrick/commit/3550f675cea0fe83e088cefef5e49012dec7a32b) to see if I'm conceptualizing `finalize()` correctly?

**Comment by bbengfort** [comment]
@rebeccabilbro yep, this is exactly what I had in mind. The `ClassificationReport.finalize` method is doing non-data related work setting tick marks, labels, titles, etc. The colorbar may or may not go into finalize (it's loosely data related), but it's perfectly fine here. The `ClassificationReport.poof` method is mostly there (except the `savefig`/`show` thing we had discussed) but it calls `finalize` at exactly the right place. 

The only minor issue is the return of the ax. I suggest that `finalize` does not return ax for the time being. We can discuss why this is a problem in person or over hangouts, I feel like it might be tough to explain in this issue without a lot of text. 

To finish this issue:

- [ ] Implement [`Visualizer.poof`](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/base.py#L54) with a docstring such that it takes `outpath` and `kwargs` arguments and implements `savefig` or `show` as in [`ParallelCoordinates.poof`](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/features/pcoords.py#L197) as well as calls `finalize()` as in the `ClassificationReport.poof` method. 
- [ ] Implement a noop [`Visualizer.finalize`] method that takes the same signature as the `ClassificationReport.finalize`. 
- [ ] Remove `ScoreVisualizer.poof` 
- [ ] Remove `ModelVisualizer.poof`
- [ ] Remove  [`return self.ax`](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/classifier.py#L209) in `ClassificationReport.finalize`
- [ ] Implement `ROCAUC.finalize` and remove `ROCAUC.poof` 
- [ ] Implement `ClassBalance.finalize` and remove `ClassBalance.poof` 
- [ ] Implement `PredictionError.finalize` and remove `PredictionError.poof`
- [ ] Implement `ResidualsPlot.finalize` and remove `ResidualsPlot.poof`
- [ ] Remove `FeatureVisualizer.poof`
- [ ] Implement `ParallelCoordinates.finalize` and remove `ParallelCoordinates.poof` 
- [ ] Implement `RadialVisualizer.finalize` and remove `RadialVisualizer.poof` 
- [ ] Implement `Rank2D.finalize` and remove `Rank2D.poof` 

This won't be "easy" in the sense of what I meant by easy per our previous discussion -- this will definitely cause breaking changes that the tests won't catch. However, this kind of work is careful craftsman work that is good for you to dig into. Be fearless because we have a version history via Git, we can recover! 

My suggestion is to create a small python script that runs the visualizer before you make a change (saving the figure), make the change, then rerun and compare the images. Feel free to text or chat with me if you have any questions. 

Also, for reference there are two ways to implement a noop function in Python:

```python
def myfunc():
    pass 
```

or 

```python
def myfunc():
     return 
``` 

Of these, I consider the former a true noop, since the latter returns `None`.

**Comment by rebeccabilbro** [comment]
Resolve Travis build failures by removing these tests: 

- [ ] tests/test_base.py
- [ ] tests/test_features/test_base.py

**Comment by rebeccabilbro** [comment]
Next run the examples notebook to see if everything still works
