### ISSUE TITLE
Seems impossible to combine clustering and clustering distance ....

### ISSUE THREAD

**Issue by jeromemassot** [DistrictDataLabs/yellowbrick#784]
Hi team,

I just want to send your this feedback about my impossibility to combine clustering and interclusteringdistance computation in a consistent way. This is an example of code I have problem with:

- in the first call, I create my tokens from a list of words
- in a second call, I create my cluster using clusters = KMeans(n_clusters=nb_k) and I SEND BACK the clusters
- in a third call, I compute the intercluster distance USING these clusters and the tokens used for building the clusters model.

```
# tokenize
tokens = tokenize(hosts_list, tfidf=False)

# clusterize the tokens
clusters = clustering_entities(tokens, nb_k)

# intercluster distances
intercluster_distance(tokens, clusters)
```

The problem is that there is an unconsistency between the labels of clusters as displayed in the first clustering_entities and the labels of clusters as displayed in the second interdistance display.

Why?

Thanks 

Best regards

Jerome

**Comment by lwgray** [comment]
hi jerome thanks for bringing this to our attention.  We are on a short 2 week hiatus and will reply when we return.

**Comment by percygautam** [comment]
I wanted to reproduce the problem you are facing, Can you specify the dataset you're working on?

**Comment by rebeccabilbro** [comment]
Bonjour @jeromemassot and apologies that you were having trouble with the [Intercluster Distance Map Visualizer](https://www.scikit-yb.org/en/develop/api/cluster/icdm.html#intercluster-distance-maps)! We would like to help, but unfortunately the information you have provided thus far is not sufficient for us to replicate or diagnose the error you are experiencing. 

It would be most helpful if you could send us a link to a gist or attach a notebook so that we could understand better what is happening in your `tokenize` and `clustering_entities` functions. 

In addition, if you could be more specific about how the problem is manifesting, it would really help us in figuring out how to solve it. Could you please either copy the traceback error or show an example plot that you are getting that is not what you were expecting?

Otherwise, if you have already resolved the issue in the meantime, please feel free to post your solution and close out this issue!

**Comment by rebeccabilbro** [comment]
Hi @jeromemassot &mdash; I'm hoping the staleness of the thread means that you found a resolution to the problem and are blazing ahead! 😄 If so, feel free to chime back in with the fix in case another YB user experiences it in the future. Since it's gone a bit quiet here and we're missing some key details, I'm going to go ahead and close this issue for now. However, if you find that the problem is persisting, please go ahead and reopen this issue with the additional details so that we can replicate & diagnose it! Thanks again for using Yellowbrick!
