### ISSUE TITLE
With Jupyter Lab, axe seems to do nothing when set in visualizer

### ISSUE THREAD

**Issue by jeromemassot** [DistrictDataLabs/yellowbrick#785]
**Describe the bug**
I send an axe to any visualizer function but it is not taken into account.

**To Reproduce**

```python
# Steps to reproduce the behavior (code snippet):
```
fig, axes = plt.subplots(1, 2, figsize=(17,8))
visualizer = FreqDistVisualizer(features=features, legend_loc="lower right", ax=axes[1])
```

**Expected behavior**
The graph should be displayed in the second axe of the subplot.

**Desktop (please complete the following information):**
 - OS: Win10
 - Python Version 3.6.5
- Jupyter Lab
 - Yellowbrick Version 0.9

**Comment by lwgray** [comment]
hi jerome thanks for bringing this to our attention.  We are on a short 2 week hiatus and will take a look at this when we return.

**Comment by naresh-bachwani** [comment]
![Screenshot (119)](https://user-images.githubusercontent.com/43993586/54532209-3b071300-49ad-11e9-8df1-9ba28f04e13e.png)
Hey @jeromemassot. I got these results with the same code. Is this your desired result?

**Comment by jeromemassot** [comment]
Hi,

in fact, it is more a problem with the axes[0]

Thanks
Best regards

Jerome

Le lun. 18 mars 2019 à 06:10, naresh-bachwani <notifications@github.com> a
écrit :

**Comment by naresh-bachwani** [comment]
It works well for me in both cases. Show me the code for which it doesn't work.

**Comment by rebeccabilbro** [comment]
Bon retour @jeromemassot! Would you mind sharing the notebook you were working in when you experienced the problem? Unfortunately the information you've provided so far has not been enough for us to replicate it. 

I'm guessing the answer isn't as simple as you not calling `poof` 😉, but if you could share the full code, that would be a great help! 

Also, could you please provide more detail about what you observed? Empty axes? Nothing? 

There's a small chance that this is related to #380

**Comment by rebeccabilbro** [comment]
Hi again @jeromemassot &mdash; hoping that you found a resolution to the problem and have already moved on! If so, feel free to chime back in 💁‍♂️ with the fix 🔧 in case another YB user experiences the same thing in the future.  Since it's gone a bit quiet here and we're missing some key details, I'm going to go ahead and close this issue for now. However, if you find that the problem is persisting, please go ahead and reopen this issue with the additional details so that we can replicate & diagnose it! Thanks for checking out Yellowbrick!
