### ISSUE TITLE
Updates to DESCRIPTION.rst

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#857]
The `DESCRIPTION.rst` file in the root of our project directory is the file that determines what is displayed on both PyPI and Anaconda Cloud. This file could use some love as a result (both in terms of content and grammar). 

Additionally, if PyPI supports it, it would be better to have this file as Markdown rather than reStructuredText because Anaconda Cloud requires Markdown and right now we have to manually edit that page. However, PyPI should be the priority for deployment. 

Note that this file is loaded by `setup.py` into the `long_description` field of the setup function.

Todo Items:

- [x] Determine if PyPI will render Markdown in addition to reStructuredText
- [x] Convert `DESCRIPTION.rst` to `DESCRIPTION.md` if yes to above 
- [x] Add new YB galleray image to replace the old one (see below)
- [x] Edit the DESCRIPTION file for both content and grammar 

![yellowbrick](https://user-images.githubusercontent.com/745966/58140527-99e74380-7c0d-11e9-96c6-61a40969957a.png)

**Comment by Kautumn06** [comment]
Hi @bbengfort, this is a great idea! I've looked into this further and [PyPi](https://packaging.python.org/guides/making-a-pypi-friendly-readme/) does support this file as either plain text, Markdown (GitHub flavored by default) or reStructuredText (however, without the Sphinx extensions). I'll also need to update `setup.py` file so that the change is reflected there as well.

As for the file's text, I also agree that it needs to be updated&mdash;especially since we have added several new visualizers since our last release. I am working on this now and I will push up some new changes over the upcoming week.
