### ISSUE TITLE
"no module named yellowbrick" error displaying in my jupyter notebook

### ISSUE THREAD

**Issue by kumar781** [DistrictDataLabs/yellowbrick#860]
**Describe the bug**

**To Reproduce**

```python
# Steps to reproduce the behavior (code snippet):
# Should include imports, dataset loading, and execution
# Add the traceback below
```

**Dataset**
Did you use a specific dataset to produce the bug? Where can we access it?

**Expected behavior**

**Traceback**

```
If applicable, add the traceback from the exception.
```

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Python Version [e.g. 2.7, 3.6, miniconda]
 - Yellowbrick Version [e.g. 0.7]

**Additional context**

**Comment by rebeccabilbro** [comment]
Hi there @kumar781 and thanks for checking out Yellowbrick! I'm sorry you're experiencing challenges with your installation, but unfortunately your issue does not provide us with any of the information we need to help you figure out what has gone wrong. We would need to know, at a minimum:

- what is your operating system?
- what is your Python version?
- what Yellowbrick version do you have installed?

The most likely case is that you have multiple versions of Python installed on your machine (e.g. both a vanilla Python and a Conda, or a Conda Python 2 and a Conda Python 3), and when you try to `pip`/`conda` installp packages, they are being installed to a different version of Python than the one you are using to launch your Jupyter notebooks.

Hope this helps!

**Comment by rebeccabilbro** [comment]
Hi again @kumar781 &dash; hope this means you were able to resolve your installation challenges! Because every combination of operating system, Python distribution, yellowbrick version and other dependencies are rather unique, I’m sure you can appreciate that it’s tough for us to guess what’s gone wrong on your end with out being able to dig into your setup. Like I mentioned, the most likely thing that went awry is that you have multiple installations of Python on your system, and you installed yellowbrick to one, but are launching Jupyter from the other. Hope this helps and thanks again for checking out yellowbrick!
