### ISSUE TITLE
Add affiliations to README and Documentation

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#895]
This issue is to update our documentation and README.md (and DESCRIPTION.rst) with our affiliations by placing an image badge and a link on those sites. 

NumFOCUS has recently sent out a badge that identifies our project as NumFOCUS affiliated:

> We are pleased to send you (see attached) an official badge identifying your project as a NumFOCUS Affiliated Project!
>
> Please feel welcome and encouraged to post this to your website and/or repo. We ask that you create a link to https://numfocus.org should someone try to click on the image.

![AffiliatedProject](https://user-images.githubusercontent.com/745966/60281851-b5600100-98d3-11e9-8fe7-3985cebb312b.png)

I have also sent an email to @ojedatony1616 to see if he was interested in doing something similar for DDL.

**Comment by bbengfort** [comment]
NumFOCUS has hosted this image on their website so we can put it up more easily with Markdown:

```
[![NumFocus Affiliated Project](https://i0.wp.com/numfocus.org/wp-content/uploads/2019/06/AffiliatedProject.png)](https://numfocus.org)
```

[![NumFocus Affiliated Project](https://i0.wp.com/numfocus.org/wp-content/uploads/2019/06/AffiliatedProject.png)](https://numfocus.org)

**Comment by Kautumn06** [comment]
Hi @bbengfort, since our affiliations are not currently mentioned in the `README.md` or `DESCRIPTION.rst` files, did you also want a new "Affiliations" section added, similar to either what we have in `about.rst`:
![about-affiliations](https://user-images.githubusercontent.com/19958803/60388089-af585480-9a7a-11e9-8d8e-24d80b874b5f.jpg)

Or in `yellowbrick/docs/governance/index.rst`:
![affiliations](https://user-images.githubusercontent.com/19958803/60388085-9f407500-9a7a-11e9-939d-a4195d63b9ef.jpg)

**Comment by bbengfort** [comment]
Hi @Kautumn06 - I'm happy to leave it up to you, but I think it might be sufficient just to have the two images in the `README.md` and `DESCRIPTION.rst` with links to the affiliations description in our about page and/or to NumFOCUS/DDL -- I don't think we need very much content here.

**Comment by bbengfort** [comment]
![DDL Affiliated Project Badge-1](https://user-images.githubusercontent.com/745966/61398750-a9e07400-a89a-11e9-8c6d-2687b121d125.png)

Here is the DDL affiliate logo.
