### ISSUE TITLE
Handle multiple figures from multiple visualizers generated by script

### ISSUE THREAD

**Issue by nickpowersys** [DistrictDataLabs/yellowbrick#924]
**Summary**
There is a behavior that may arise in situations involving multiple visualizers, such as model selection as part of a script.

Specifically, if a script calls `poof()` repeatedly, a figure window is created each time.
- Each window must be closed before the next figure is shown. Each shows up as Figure 1.
- Closing each figure window after it appears means that figure is no longer available for comparison with the others.
- Manually saving each figure one at a time before closing it is extremely slow.
- Adding `_, ax = plt.subplots()` to the script between calls to `poof()` has no effect on this behavior.

This is being referenced in connection with PR #922, which relates to the code directive for the function `visualize_model` in the Model Selection Tutorial.

A possible approach is to save each image to a file through `poof('[ESTIMATOR].png')`, then close the figure immediately after. https://github.com/DistrictDataLabs/yellowbrick/pull/922#issuecomment-511654073

**Comment by bbengfort** [comment]
@nickpowersys thanks for the comment! I think that saving the image to the file is perhaps the easiest solution in a script. Another alternative is to call `finalize()` instead of `poof()` and then do a show at the end so all windows pop up at once (make sure to create multiple figures in this case). We also have some prototype tools for adding multiple visualizers to a single figure using the `VisualizerGrid` as described in #176. We also plan to enhance visual pipelines with a "flipbook" model, e.g. #47 -- though this is also still in prototype mode.
