### ISSUE TITLE
Create YB tutorial

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#96]
We need a YB tutorial - something more ML process focused than the examples notebook and what's in the documentation. 

In other words, this is not a walk through of all the methods implemented in Yellowbrick, but an illustration of how Yellowbrick would be deployed in the course of several machine learning case studies. Something more like:

 - http://scikit-learn.org/stable/tutorial/basic/tutorial.html
 - http://scikit-learn.org/stable/tutorial/statistical_inference/supervised_learning.html
 - http://scikit-learn.org/stable/tutorial/statistical_inference/model_selection.html
 - http://scikit-learn.org/stable/tutorial/statistical_inference/unsupervised_learning.html

We'll use this tutorial for training events and also probably convert it into a blog for DDL.

**Comment by rebeccabilbro** [comment]
This might be a good candidate for refactoring with visualizers: https://github.com/georgetown-analytics/XBUS-506-01.Visual_Analytics/blob/master/select/model_selection.ipynb

**Comment by bbengfort** [comment]
January 25:

- Rebecca: mushroom case study start and iterative development 
- Ben: outline introduction to visual steering

**Comment by rebeccabilbro** [comment]
Mushroom case study complete and added to documentation in develop branch:  https://github.com/DistrictDataLabs/yellowbrick/blob/develop/docs/examples/modelselect.rst

**Comment by bbengfort** [comment]
@rebeccabilbro - just read through the mushroom case study - it looks good and I think it meets the requirements for this card; it's a clear demonstration about how a visual classification report makes it easier to conduct model selection than just looking at pure F1 scores. 

If you wanted to expand it (no reason to, though), we perhaps could include parallel coordinates to show the features. We could also adjust the scale on the classification report to go from 0.5 to 1.0 so that the difference in the scores was more distinct. I'd do this by adding a parameter to the visualizer that set the scale of scores. We could also add a ROCAUC for the LogisticRegression at the end to discuss other visual methods. But like I said, I don't think it's necessary for the case study.
