### ISSUE TITLE
n_components

### ISSUE THREAD

**Issue by aspitaleri** [DistrictDataLabs/yellowbrick#982]
Hi there,
I am new in yellobrick and I should say it is great!
Easy and quick to create PCA. I went through the manual but I couldn find the way to draw PCA using different component, e.g. 2 vs 3 and so on. 
Also the visualization 3D it is not clear how do it. I followed the tutorial but still getting the 2D projection.
Any help?
Thanks

**Comment by Kautumn06** [comment]
Hi @aspitaleri, I'm so happy to hear you're finding Yellowbrick helpful! To create a 3D PCA plot, you need to set the parameter `proj_dim=3` and ensure that you pass a `matplotlib` 3D axes to the `PCADecomposition` visualizer.

Unfortunately, without seeing your code, it's difficult to know where the problem is coming from. However, I've created a quick example here for you to use as a guide that will hopefully solve this issue.
```
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

from yellowbrick.datasets import load_credit
from yellowbrick.features import PCADecomposition

# Specify the features of interest and the target
X, y = load_credit()

# Create a figure and add a 3D axis
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# Instantiate the visualizer
visualizer = PCADecomposition(scale=True, proj_dim=3, ax=ax)
visualizer.fit_transform(X, y)
visualizer.show()
```
![image](https://user-images.githubusercontent.com/19958803/67148082-2d7a7a00-f269-11e9-90d6-db70f9c3607e.png)

**Comment by aspitaleri** [comment]
Hi @Kautumn06 
thanks a lot for your reply. 
3D is okay. it was a my mistake.

What about plot different component? I am able to plot only 1vs2. what about the rest components, e.g. 2vs3, 3vs4 and so on.

**Comment by Kautumn06** [comment]
Hi @aspitaleri &mdash; unfortunately, our implementation of PCA sets `n_components=2` (or to 3 if `proj_dim` is `3D`), so you can’t plot additional components against each other, though that would be an interesting PR we’d be happy to consider!

However, if you're interested, you also have the option to explore the relationship of these principle components with features using the `colorbar` and `heatmap` parameters, which are currently undocumented. For instance, to visualize the relationship between multiple components, we'd recommend first applying PCA and then apply a manifold such as TSNE:
![image](https://user-images.githubusercontent.com/19958803/67537338-ddf0df80-f6a8-11e9-8049-e95bf532c798.png)

I hope this has been helpful and thank you again for using Yellowbrick!
